import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { tempDir } from './helpers/temp-dir.mjs';

import {
  PROFILE_VERSION,
  adaptedCopies,
  adaptedRecord,
  changedAdaptedCopies,
  fingerprintOf,
  installedSkills,
  legacyLocalProfilePath,
  localProfilePath,
  readSuggestionMarker,
  writeSuggestionMarker,
  profilePaths,
  readProfile,
  renderRules,
  rulesPath,
  userConfig,
  writeProfile,
} from '../skills/onboard-project/scripts/profile.mjs';

const scratch = (name) => tempDir(`${name}-`);

const sampleProfile = () => ({
  version: PROFILE_VERSION,
  generatedBy: 'onboard-project 1.0.0',
  scannedAt: '2026-09-14T23:50:00Z',
  placement: 'committed',
  fingerprint: 'abc',
  skills: {
    'report-progress': { match: 'general', evidence: [], useWhen: 'delegating to agents', required: false, scope: 'global' },
    'release-notes': { match: 'strong', evidence: ['package.json has a version'], useWhen: 'about to cut a release', required: true, scope: 'project' },
  },
  declined: {},
});

test('a committed profile sits at the repository root, a local one under the user home', async () => {
  const repo = await scratch('profile-repo');
  const home = await scratch('profile-home');
  const paths = profilePaths(repo, { home });
  assert.equal(paths.committed, path.join(repo, 'skills-profile.json'));
  assert.equal(paths.local, localProfilePath(repo, { home }));
  assert.match(paths.local, /\.agents[/\\]project-profiles[/\\]/);
  assert.equal(rulesPath(repo), path.join(repo, '.claude', 'rules', 'skill-routing.md'));
});

test('a profile round-trips, and the committed copy wins over the local one', async () => {
  const repo = await scratch('profile-repo-rt');
  const home = await scratch('profile-home-rt');
  assert.equal(readProfile(repo, { home }), null);

  writeProfile(repo, { ...sampleProfile(), placement: 'local' }, { home });
  assert.equal(readProfile(repo, { home }).placement, 'local');

  writeProfile(repo, { ...sampleProfile(), placement: 'committed' }, { home });
  const found = readProfile(repo, { home });
  assert.equal(found.placement, 'committed');
  assert.equal(found.skills['release-notes'].required, true);
});

test('a corrupt profile reads as absent rather than throwing', async () => {
  const repo = await scratch('profile-repo-corrupt');
  const home = await scratch('profile-home-corrupt');
  await writeFile(path.join(repo, 'skills-profile.json'), '{ not json');
  assert.equal(readProfile(repo, { home }), null);
});

test('the fingerprint ignores key order and moves when a signal appears or disappears', () => {
  const one = fingerprintOf({ 'release-notes': ['exists:CHANGELOG.md', 'json:package.json#version'] });
  const reordered = fingerprintOf({ 'release-notes': ['json:package.json#version', 'exists:CHANGELOG.md'] });
  assert.equal(one, reordered, 'signal order changed the fingerprint');

  const more = fingerprintOf({ 'release-notes': ['exists:CHANGELOG.md', 'json:package.json#version', 'exists:.changeset/'] });
  assert.notEqual(one, more, 'a new signal did not move the fingerprint');

  const other = fingerprintOf({ 'report-progress': ['exists:CHANGELOG.md', 'json:package.json#version'] });
  assert.notEqual(one, other, 'the same signals under another skill collided');
  assert.match(one, /^[0-9a-f]{64}$/);
});

test('the rules file carries the generated-by header and one line per skill, strong first', () => {
  const rules = renderRules(sampleProfile());
  const lines = rules.split('\n');
  assert.match(lines[0], /^<!-- Generated by onboard-project/);
  assert.match(rules, /Do not edit/);
  assert.match(rules, /^# Skill routing for this project$/m);
  const strong = rules.indexOf('`release-notes`');
  const general = rules.indexOf('`report-progress`');
  assert.ok(strong > 0 && general > strong, 'a general match was listed before a strong one');
  assert.match(rules, /- about to cut a release \u2192 `release-notes`/);
  assert.ok(rules.endsWith('\n'));
  // The evidence stays in the profile: the always-loaded file holds one line per skill.
  assert.doesNotMatch(rules, /package\.json has a version/);
});

test('rendering is deterministic, which is what lets the check detect a hand edit', () => {
  assert.equal(renderRules(sampleProfile()), renderRules(sampleProfile()));
});

test('installed skills are read from both lock files and both skill directories', async () => {
  const repo = await scratch('profile-repo-installed');
  const home = await scratch('profile-home-installed');
  await writeFile(path.join(repo, 'skills-lock.json'), JSON.stringify({
    version: 1,
    skills: { 'release-notes': { source: 'crissmoldovan/agent-skills', sourceType: 'github' } },
  }));
  await mkdir(path.join(home, '.agents'), { recursive: true });
  await writeFile(path.join(home, '.agents', '.skill-lock.json'), JSON.stringify({
    version: 1,
    skills: { 'report-progress': { source: 'crissmoldovan/agent-skills', sourceType: 'github' } },
  }));
  await mkdir(path.join(home, '.claude', 'skills', 'blast-area'), { recursive: true });
  await writeFile(path.join(home, '.claude', 'skills', 'blast-area', 'SKILL.md'), '---\nname: blast-area\n---\n');
  await mkdir(path.join(repo, '.claude', 'skills', 'decision-journal'), { recursive: true });
  await writeFile(path.join(repo, '.claude', 'skills', 'decision-journal', 'SKILL.md'), '---\nname: decision-journal\n---\n');

  const installed = installedSkills({ repoRoot: repo, home });
  assert.equal(installed.get('release-notes'), 'project');
  assert.equal(installed.get('report-progress'), 'global');
  assert.equal(installed.get('blast-area'), 'global');
  assert.equal(installed.get('decision-journal'), 'project');
  assert.equal(installed.has('github-webhooks'), false);
});

test('the user config gives the owners whose repositories take committed files', async () => {
  const home = await scratch('profile-home-config');
  assert.deepEqual(userConfig({ home }).commitOwners, [], 'an absent config is an empty list, not an error');
  await mkdir(path.join(home, '.agents'), { recursive: true });
  await writeFile(path.join(home, '.agents', 'onboard-project.json'), JSON.stringify({ commitOwners: ['an-owner'] }));
  assert.deepEqual(userConfig({ home }).commitOwners, ['an-owner']);
});

test('a profile is written atomically, so two sessions cannot leave half a file', async () => {
  const repo = await scratch('profile-repo-atomic');
  const home = await scratch('profile-home-atomic');
  writeProfile(repo, sampleProfile(), { home });
  const written = JSON.parse(await readFile(path.join(repo, 'skills-profile.json'), 'utf8'));
  assert.equal(written.version, PROFILE_VERSION);
  const entries = (await import('node:fs/promises')).readdir;
  assert.equal((await entries(repo)).filter((name) => name.includes('.tmp')).length, 0, 'a temporary file was left behind');
});


// ---- review of 0.22.0: ordering, path collisions, the suggestion marker -------------------------

test('the routing file orders by code point, so two machines with different locales render the same bytes', () => {
  const profile = {
    ...sampleProfile(),
    skills: {
      'alpha-skill': { match: 'strong', evidence: [], useWhen: 'lower-case first by locale', required: true, scope: 'project' },
      'Zeta-skill': { match: 'strong', evidence: [], useWhen: 'upper-case first by code point', required: true, scope: 'project' },
    },
  };
  const rules = renderRules(profile);
  // localeCompare puts `alpha` before `Zeta` in most locales; code point order puts `Z` (0x5A) first.
  assert.ok(rules.indexOf('`Zeta-skill`') < rules.indexOf('`alpha-skill`'), 'the order depends on the runtime locale');
});

test('two repositories whose paths differ only by a separator get different local profiles', () => {
  const home = path.join(path.sep, 'h');
  const dashed = localProfilePath(path.join(path.sep, 'w', 'foo-bar'), { home });
  const nested = localProfilePath(path.join(path.sep, 'w', 'foo', 'bar'), { home });
  assert.notEqual(dashed, nested);
  // The 0.22.0 name collided, which is exactly why it is only ever read as a fallback now.
  assert.equal(
    legacyLocalProfilePath(path.join(path.sep, 'w', 'foo-bar'), { home }),
    legacyLocalProfilePath(path.join(path.sep, 'w', 'foo', 'bar'), { home }),
  );
});

test('a local profile records its repository, and one written for another repository is not read', async () => {
  const home = await scratch('profile-home-owner');
  const mine = await scratch('profile-repo-mine');
  writeProfile(mine, { ...sampleProfile(), placement: 'local' }, { home });
  const written = JSON.parse(await readFile(localProfilePath(mine, { home }), 'utf8'));
  assert.equal(written.repo, path.resolve(mine), 'a local profile does not say which repository it belongs to');

  // A committed profile must not carry an absolute path: it is published with the repository.
  const committed = await scratch('profile-repo-committed');
  writeProfile(committed, { ...sampleProfile(), placement: 'committed' }, { home });
  const onDisk = JSON.parse(await readFile(path.join(committed, 'skills-profile.json'), 'utf8'));
  assert.equal(onDisk.repo, undefined, 'a committed profile carries a machine path');

  // A legacy-named file that belongs to some other repository is refused.
  const other = await scratch('profile-repo-other');
  await mkdir(path.dirname(legacyLocalProfilePath(other, { home })), { recursive: true });
  await writeFile(legacyLocalProfilePath(other, { home }), JSON.stringify({ ...sampleProfile(), placement: 'local', repo: '/somewhere/else' }));
  assert.equal(readProfile(other, { home }), null, 'another repository\'s profile was read as this one\'s');
});

test('a 0.22.0 local profile is not read, because its name cannot say which repository it belongs to', async () => {
  // It has no \`repo\` field, and its name is the collision itself: \`foo-bar\` and \`foo/bar\` share it.
  // Reading it would hand one repository another's skills — and refresh keeps listed skills now.
  const home = await scratch('profile-home-legacy');
  const repo = await scratch('profile-repo-legacy');
  await mkdir(path.dirname(legacyLocalProfilePath(repo, { home })), { recursive: true });
  await writeFile(legacyLocalProfilePath(repo, { home }), JSON.stringify({ ...sampleProfile(), placement: 'local' }));
  assert.equal(readProfile(repo, { home }), null);
});

test('the suggestion marker is not a profile, and is read and written on its own', async () => {
  const home = await scratch('profile-home-marker');
  const repo = await scratch('profile-repo-marker');
  assert.equal(readSuggestionMarker(repo, { home }), null);
  writeSuggestionMarker(repo, { home });
  assert.equal(readProfile(repo, { home }), null, 'the marker was read as a profile');
  assert.equal(readSuggestionMarker(repo, { home })?.onboarding, 'suggested');

  // The 0.22.0 marker lived at the colliding name too; it is not read either — the worst this costs
  // is one more suggestion, where reading it could silence one for the wrong repository.
  const old = await scratch('profile-repo-marker-legacy');
  await mkdir(path.dirname(legacyLocalProfilePath(old, { home })), { recursive: true });
  await writeFile(legacyLocalProfilePath(old, { home }), JSON.stringify({ version: 1, onboarding: 'suggested', at: '2026-09-15' }));
  assert.equal(readProfile(old, { home }), null);
  assert.equal(readSuggestionMarker(old, { home }), null);
});


// ---- adapted copies: a skill a project has adapted is present, and the routing names the copy ----

/** An adapted copy as update-agent-skills' composer leaves it: a skill folder and its lock. */
async function adaptedCopy(repo, name, base, { entry = 'SKILL.md', ref = 'v1.4.0', tree = 'b'.repeat(40), directory = path.join('.claude', 'skills'), lock } = {}) {
  const folder = path.join(repo, directory, name);
  await mkdir(folder, { recursive: true });
  await writeFile(path.join(folder, 'SKILL.md'), `---\nname: ${name}\n---\n`);
  await writeFile(path.join(folder, 'adapted.lock.json'), typeof lock === 'string' ? lock : JSON.stringify(lock ?? {
    version: 1,
    name,
    base: { source: 'https://github.com/an-owner/a-pack', skill: base, entry, ref, commit: 'a'.repeat(40), tree },
    files: {},
  }, null, 2));
}

test('adapted copies are read from the repository\'s own skill folders, by the skill each adapts', async () => {
  const repo = await scratch('profile-repo-adapted');
  await adaptedCopy(repo, 'ship-a-pack', 'release-notes', { entry: 'references/release-pack.md' });
  await adaptedCopy(repo, 'cut-a-release', 'release-notes');
  await adaptedCopy(repo, 'ask-the-owner', 'request-answers', { directory: path.join('.agents', 'skills') });
  // A skill folder with no lock is an ordinary install, not an adapted copy.
  await mkdir(path.join(repo, '.claude', 'skills', 'plain-skill'), { recursive: true });
  await writeFile(path.join(repo, '.claude', 'skills', 'plain-skill', 'SKILL.md'), '---\nname: plain-skill\n---\n');

  const { byBase, ignored } = adaptedCopies(repo);
  assert.deepEqual(ignored, []);
  assert.deepEqual([...byBase.keys()], ['release-notes', 'request-answers']);
  assert.deepEqual(byBase.get('release-notes'), [
    { name: 'cut-a-release', entry: 'SKILL.md', ref: 'v1.4.0', tree: 'b'.repeat(40) },
    { name: 'ship-a-pack', entry: 'references/release-pack.md', ref: 'v1.4.0', tree: 'b'.repeat(40) },
  ]);
  assert.equal(byBase.get('request-answers')[0].name, 'ask-the-owner');
  assert.deepEqual(adaptedRecord(byBase)['release-notes'].map((copy) => copy.name), ['cut-a-release', 'ship-a-pack']);
});

test('a lock that cannot be read stands in for nothing, and is named', async () => {
  const repo = await scratch('profile-repo-adapted-unreadable');
  await adaptedCopy(repo, 'torn', 'release-notes', { lock: '{ not json' });
  await adaptedCopy(repo, 'no-tree', 'release-notes', { tree: 'abc' });
  await adaptedCopy(repo, 'release-notes', 'release-notes');
  await adaptedCopy(repo, 'renamed', 'release-notes', { lock: { version: 1, name: 'another-name', base: { skill: 'release-notes', ref: 'v1.4.0', tree: 'b'.repeat(40) } } });
  await adaptedCopy(repo, 'bad-entry', 'release-notes', { entry: '../outside.md' });
  await adaptedCopy(repo, 'later-version', 'release-notes', { lock: { version: 2, base: { skill: 'release-notes', ref: 'v1.4.0', tree: 'b'.repeat(40) } } });
  // A folder no routing line could name, with a lock that names nothing: counted, it would silence
  // the missing report and then be dropped from the profile, reading as changed at every start.
  await adaptedCopy(repo, 'Ask_Here', 'release-notes', { lock: { version: 1, base: { skill: 'release-notes', ref: 'v1.4.0', tree: 'b'.repeat(40) } } });

  const { byBase, ignored } = adaptedCopies(repo);
  assert.equal(byBase.size, 0, 'an unreadable lock stood in for a skill');
  assert.equal(ignored.length, 7, ignored.join('\n'));
  assert.ok(ignored.some((line) => /^\.claude\/skills\/torn: /.test(line)));
  assert.ok(ignored.some((line) => /takes the name of the skill it adapts/.test(line)));
  assert.ok(ignored.some((line) => /not its own folder/.test(line)));
  assert.ok(ignored.some((line) => /^\.claude\/skills\/later-version: .*has version 2, which this skill does not read: if a newer composer wrote it, update onboard-project$/.test(line)));
  assert.ok(ignored.some((line) => /^\.claude\/skills\/Ask_Here: the folder name is not a skill name/.test(line)));
});

test('a second folder of one name is named when its lock says something else, and is quiet when it is the same copy', async () => {
  const repo = await scratch('profile-repo-adapted-twice');
  await adaptedCopy(repo, 'cut-a-release', 'release-notes');
  await adaptedCopy(repo, 'cut-a-release', 'release-notes', { directory: path.join('.agents', 'skills') });
  const same = adaptedCopies(repo);
  assert.deepEqual(same.ignored, [], 'the same copy in both folders was reported');
  assert.equal(same.byBase.get('release-notes').length, 1);

  await adaptedCopy(repo, 'cut-a-release', 'request-answers', { directory: path.join('.agents', 'skills') });
  const differing = adaptedCopies(repo);
  assert.deepEqual(differing.ignored, ['.agents/skills/cut-a-release: has the name of .claude/skills/cut-a-release, which is read first, and its lock says something else']);
  assert.deepEqual([...differing.byBase.keys()], ['release-notes'], 'the folder read second was counted');
});

test('the routing names a skill\'s adapted copies instead of the skill, and says what each adapts', () => {
  const profile = {
    ...sampleProfile(),
    adapted: {
      'release-notes': [
        { name: 'cut-a-release', entry: 'SKILL.md', ref: 'v1.4.0', tree: 'b'.repeat(40) },
        { name: 'ship-a-pack', entry: 'references/release-pack.md', ref: 'v1.4.0', tree: 'b'.repeat(40) },
      ],
      'report-progress': [{ name: 'say-where-we-are', entry: 'SKILL.md', ref: 'v1.4.0', tree: 'c'.repeat(40) }],
      // A copy of a skill the profile does not list adds no line.
      'not-listed': [{ name: 'orphan-copy', entry: 'SKILL.md', ref: 'v1.4.0', tree: 'd'.repeat(40) }],
    },
  };
  const rules = renderRules(profile);
  assert.match(rules, /^- about to cut a release → `cut-a-release` or `ship-a-pack` \(from references\/release-pack\.md\), this repository's adapted copies of `release-notes`$/m);
  assert.match(rules, /^- delegating to agents → `say-where-we-are`, this repository's adapted copy of `report-progress`$/m);
  assert.doesNotMatch(rules, /→ `release-notes`/, 'the routing still sends the task to the generic skill');
  assert.doesNotMatch(rules, /orphan-copy/);
  assert.match(rules, /load that copy rather than the skill it adapts/);
  assert.match(rules, /or only the file named after "from"/);
  assert.match(rules, /load the one whose own description fits the task/);
  assert.doesNotMatch(rules, /whole text/, 'the routing says a copy over one file carries the whole skill');
  assert.equal(renderRules(profile), renderRules(structuredClone(profile)));
});

test('a profile with no adapted copy renders the bytes it rendered before copies were read', () => {
  // A routing file committed by an earlier release must not read as drift after an upgrade.
  const before = [
    '<!-- Generated by onboard-project from skills-profile.json. Do not edit; change the profile and run refresh. -->',
    '# Skill routing for this project',
    '',
    'These skills were chosen from evidence in this repository. Load one when the moment matches;',
    'nothing here is enforced.',
    '',
    '- about to cut a release → `release-notes`',
    '- delegating to agents → `report-progress`',
    '',
  ].join('\n');
  assert.equal(renderRules(sampleProfile()), before);
  assert.equal(renderRules({ ...sampleProfile(), adapted: {} }), before);
  assert.equal(renderRules({ ...sampleProfile(), adapted: { 'release-notes': 'not a list' } }), before);
  assert.doesNotMatch(before, /adapted/);
});

test('an adapted skill the scan did not match is routed after the strong ones and before the rest', () => {
  const profile = {
    ...sampleProfile(),
    skills: {
      ...sampleProfile().skills,
      'mine-something': { match: 'adapted', evidence: ['adapted here as find-what-was-said'], useWhen: 'asked for by name', required: false, scope: 'project' },
      'a-weak-one': { match: 'weak', evidence: [], useWhen: 'a weak suggestion', required: false, scope: 'global' },
    },
    adapted: { 'mine-something': [{ name: 'find-what-was-said', entry: 'SKILL.md', ref: 'v1.4.0', tree: 'e'.repeat(40) }] },
  };
  const rules = renderRules(profile);
  const at = (needle) => rules.indexOf(needle);
  assert.ok(at('`release-notes`') < at('`find-what-was-said`'), 'an adapted line came before a strong one');
  assert.ok(at('`find-what-was-said`') < at('`a-weak-one`'), 'an adapted line came after a weak one');
  assert.ok(at('`a-weak-one`') < at('`report-progress`'), 'a weak line came after a general one');
});

test('the adapted copies that changed are named: added, removed, moved to another skill, or re-pinned', () => {
  const copy = (name, overrides = {}) => ({ name, entry: 'SKILL.md', ref: 'v1.4.0', tree: 'b'.repeat(40), ...overrides });
  const recorded = { 'release-notes': [copy('cut-a-release'), copy('ship-a-pack')], 'request-answers': [copy('ask-the-owner')] };
  const same = new Map([['release-notes', [copy('cut-a-release'), copy('ship-a-pack')]], ['request-answers', [copy('ask-the-owner')]]]);
  assert.deepEqual(changedAdaptedCopies(recorded, same), []);

  const now = new Map([
    ['release-notes', [copy('cut-a-release', { ref: 'v1.5.0', tree: 'c'.repeat(40) })]],
    ['report-progress', [copy('ask-the-owner')]],
    ['request-answers', [copy('new-copy')]],
  ]);
  assert.deepEqual(changedAdaptedCopies(recorded, now), ['ask-the-owner', 'cut-a-release', 'new-copy', 'ship-a-pack']);
  // A profile written before copies were read has no map, and reads as one that recorded none.
  assert.deepEqual(changedAdaptedCopies(undefined, new Map()), []);
  assert.deepEqual(changedAdaptedCopies(undefined, same), ['ask-the-owner', 'cut-a-release', 'ship-a-pack']);
});
