import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { tempDir } from './helpers/temp-dir.mjs';

import {
  PROFILE_VERSION,
  fingerprintOf,
  installedSkills,
  legacyLocalProfilePath,
  localProfilePath,
  readSuggestionMarker,
  writeSuggestionMarker,
  profilePaths,
  readProfile,
  renderRules,
  rulesPath,
  userConfig,
  writeProfile,
} from '../skills/onboard-project/scripts/profile.mjs';

const scratch = (name) => tempDir(`${name}-`);

const sampleProfile = () => ({
  version: PROFILE_VERSION,
  generatedBy: 'onboard-project 1.0.0',
  scannedAt: '2026-09-14T23:50:00Z',
  placement: 'committed',
  fingerprint: 'abc',
  skills: {
    'report-progress': { match: 'general', evidence: [], useWhen: 'delegating to agents', required: false, scope: 'global' },
    'release-notes': { match: 'strong', evidence: ['package.json has a version'], useWhen: 'about to cut a release', required: true, scope: 'project' },
  },
  declined: {},
});

test('a committed profile sits at the repository root, a local one under the user home', async () => {
  const repo = await scratch('profile-repo');
  const home = await scratch('profile-home');
  const paths = profilePaths(repo, { home });
  assert.equal(paths.committed, path.join(repo, 'skills-profile.json'));
  assert.equal(paths.local, localProfilePath(repo, { home }));
  assert.match(paths.local, /\.agents[/\\]project-profiles[/\\]/);
  assert.equal(rulesPath(repo), path.join(repo, '.claude', 'rules', 'skill-routing.md'));
});

test('a profile round-trips, and the committed copy wins over the local one', async () => {
  const repo = await scratch('profile-repo-rt');
  const home = await scratch('profile-home-rt');
  assert.equal(readProfile(repo, { home }), null);

  writeProfile(repo, { ...sampleProfile(), placement: 'local' }, { home });
  assert.equal(readProfile(repo, { home }).placement, 'local');

  writeProfile(repo, { ...sampleProfile(), placement: 'committed' }, { home });
  const found = readProfile(repo, { home });
  assert.equal(found.placement, 'committed');
  assert.equal(found.skills['release-notes'].required, true);
});

test('a corrupt profile reads as absent rather than throwing', async () => {
  const repo = await scratch('profile-repo-corrupt');
  const home = await scratch('profile-home-corrupt');
  await writeFile(path.join(repo, 'skills-profile.json'), '{ not json');
  assert.equal(readProfile(repo, { home }), null);
});

test('the fingerprint ignores key order and moves when a signal appears or disappears', () => {
  const one = fingerprintOf({ 'release-notes': ['exists:CHANGELOG.md', 'json:package.json#version'] });
  const reordered = fingerprintOf({ 'release-notes': ['json:package.json#version', 'exists:CHANGELOG.md'] });
  assert.equal(one, reordered, 'signal order changed the fingerprint');

  const more = fingerprintOf({ 'release-notes': ['exists:CHANGELOG.md', 'json:package.json#version', 'exists:.changeset/'] });
  assert.notEqual(one, more, 'a new signal did not move the fingerprint');

  const other = fingerprintOf({ 'report-progress': ['exists:CHANGELOG.md', 'json:package.json#version'] });
  assert.notEqual(one, other, 'the same signals under another skill collided');
  assert.match(one, /^[0-9a-f]{64}$/);
});

test('the rules file carries the generated-by header and one line per skill, strong first', () => {
  const rules = renderRules(sampleProfile());
  const lines = rules.split('\n');
  assert.match(lines[0], /^<!-- Generated by onboard-project/);
  assert.match(rules, /Do not edit/);
  assert.match(rules, /^# Skill routing for this project$/m);
  const strong = rules.indexOf('`release-notes`');
  const general = rules.indexOf('`report-progress`');
  assert.ok(strong > 0 && general > strong, 'a general match was listed before a strong one');
  assert.match(rules, /- about to cut a release \u2192 `release-notes`/);
  assert.ok(rules.endsWith('\n'));
  // The evidence stays in the profile: the always-loaded file holds one line per skill.
  assert.doesNotMatch(rules, /package\.json has a version/);
});

test('rendering is deterministic, which is what lets the check detect a hand edit', () => {
  assert.equal(renderRules(sampleProfile()), renderRules(sampleProfile()));
});

test('installed skills are read from both lock files and both skill directories', async () => {
  const repo = await scratch('profile-repo-installed');
  const home = await scratch('profile-home-installed');
  await writeFile(path.join(repo, 'skills-lock.json'), JSON.stringify({
    version: 1,
    skills: { 'release-notes': { source: 'crissmoldovan/agent-skills', sourceType: 'github' } },
  }));
  await mkdir(path.join(home, '.agents'), { recursive: true });
  await writeFile(path.join(home, '.agents', '.skill-lock.json'), JSON.stringify({
    version: 1,
    skills: { 'report-progress': { source: 'crissmoldovan/agent-skills', sourceType: 'github' } },
  }));
  await mkdir(path.join(home, '.claude', 'skills', 'blast-area'), { recursive: true });
  await writeFile(path.join(home, '.claude', 'skills', 'blast-area', 'SKILL.md'), '---\nname: blast-area\n---\n');
  await mkdir(path.join(repo, '.claude', 'skills', 'decision-journal'), { recursive: true });
  await writeFile(path.join(repo, '.claude', 'skills', 'decision-journal', 'SKILL.md'), '---\nname: decision-journal\n---\n');

  const installed = installedSkills({ repoRoot: repo, home });
  assert.equal(installed.get('release-notes'), 'project');
  assert.equal(installed.get('report-progress'), 'global');
  assert.equal(installed.get('blast-area'), 'global');
  assert.equal(installed.get('decision-journal'), 'project');
  assert.equal(installed.has('github-webhooks'), false);
});

test('the user config gives the owners whose repositories take committed files', async () => {
  const home = await scratch('profile-home-config');
  assert.deepEqual(userConfig({ home }).commitOwners, [], 'an absent config is an empty list, not an error');
  await mkdir(path.join(home, '.agents'), { recursive: true });
  await writeFile(path.join(home, '.agents', 'onboard-project.json'), JSON.stringify({ commitOwners: ['an-owner'] }));
  assert.deepEqual(userConfig({ home }).commitOwners, ['an-owner']);
});

test('a profile is written atomically, so two sessions cannot leave half a file', async () => {
  const repo = await scratch('profile-repo-atomic');
  const home = await scratch('profile-home-atomic');
  writeProfile(repo, sampleProfile(), { home });
  const written = JSON.parse(await readFile(path.join(repo, 'skills-profile.json'), 'utf8'));
  assert.equal(written.version, PROFILE_VERSION);
  const entries = (await import('node:fs/promises')).readdir;
  assert.equal((await entries(repo)).filter((name) => name.includes('.tmp')).length, 0, 'a temporary file was left behind');
});


// ---- review of 0.22.0: ordering, path collisions, the suggestion marker -------------------------

test('the routing file orders by code point, so two machines with different locales render the same bytes', () => {
  const profile = {
    ...sampleProfile(),
    skills: {
      'alpha-skill': { match: 'strong', evidence: [], useWhen: 'lower-case first by locale', required: true, scope: 'project' },
      'Zeta-skill': { match: 'strong', evidence: [], useWhen: 'upper-case first by code point', required: true, scope: 'project' },
    },
  };
  const rules = renderRules(profile);
  // localeCompare puts `alpha` before `Zeta` in most locales; code point order puts `Z` (0x5A) first.
  assert.ok(rules.indexOf('`Zeta-skill`') < rules.indexOf('`alpha-skill`'), 'the order depends on the runtime locale');
});

test('two repositories whose paths differ only by a separator get different local profiles', () => {
  const home = path.join(path.sep, 'h');
  const dashed = localProfilePath(path.join(path.sep, 'w', 'foo-bar'), { home });
  const nested = localProfilePath(path.join(path.sep, 'w', 'foo', 'bar'), { home });
  assert.notEqual(dashed, nested);
  // The 0.22.0 name collided, which is exactly why it is only ever read as a fallback now.
  assert.equal(
    legacyLocalProfilePath(path.join(path.sep, 'w', 'foo-bar'), { home }),
    legacyLocalProfilePath(path.join(path.sep, 'w', 'foo', 'bar'), { home }),
  );
});

test('a local profile records its repository, and one written for another repository is not read', async () => {
  const home = await scratch('profile-home-owner');
  const mine = await scratch('profile-repo-mine');
  writeProfile(mine, { ...sampleProfile(), placement: 'local' }, { home });
  const written = JSON.parse(await readFile(localProfilePath(mine, { home }), 'utf8'));
  assert.equal(written.repo, path.resolve(mine), 'a local profile does not say which repository it belongs to');

  // A committed profile must not carry an absolute path: it is published with the repository.
  const committed = await scratch('profile-repo-committed');
  writeProfile(committed, { ...sampleProfile(), placement: 'committed' }, { home });
  const onDisk = JSON.parse(await readFile(path.join(committed, 'skills-profile.json'), 'utf8'));
  assert.equal(onDisk.repo, undefined, 'a committed profile carries a machine path');

  // A legacy-named file that belongs to some other repository is refused.
  const other = await scratch('profile-repo-other');
  await mkdir(path.dirname(legacyLocalProfilePath(other, { home })), { recursive: true });
  await writeFile(legacyLocalProfilePath(other, { home }), JSON.stringify({ ...sampleProfile(), placement: 'local', repo: '/somewhere/else' }));
  assert.equal(readProfile(other, { home }), null, 'another repository\'s profile was read as this one\'s');
});

test('a 0.22.0 local profile is still read from its old name', async () => {
  const home = await scratch('profile-home-legacy');
  const repo = await scratch('profile-repo-legacy');
  await mkdir(path.dirname(legacyLocalProfilePath(repo, { home })), { recursive: true });
  await writeFile(legacyLocalProfilePath(repo, { home }), JSON.stringify({ ...sampleProfile(), placement: 'local' }));
  assert.equal(readProfile(repo, { home })?.placement, 'local');
});

test('the suggestion marker is not a profile, and is read and written on its own', async () => {
  const home = await scratch('profile-home-marker');
  const repo = await scratch('profile-repo-marker');
  assert.equal(readSuggestionMarker(repo, { home }), null);
  writeSuggestionMarker(repo, { home });
  assert.equal(readProfile(repo, { home }), null, 'the marker was read as a profile');
  assert.equal(readSuggestionMarker(repo, { home })?.onboarding, 'suggested');

  // The 0.22.0 marker lived at the old profile name; it still counts as a marker, never as a profile.
  const old = await scratch('profile-repo-marker-legacy');
  await mkdir(path.dirname(legacyLocalProfilePath(old, { home })), { recursive: true });
  await writeFile(legacyLocalProfilePath(old, { home }), JSON.stringify({ version: 1, onboarding: 'suggested', at: '2026-09-15' }));
  assert.equal(readProfile(old, { home }), null);
  assert.equal(readSuggestionMarker(old, { home })?.onboarding, 'suggested');
});
