import { appendFile, mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';

export type ChildState = 'created' | 'starting' | 'running' | 'waiting' | 'completed' | 'failed' | 'cancelled' | 'lost';
export type LifecycleKind = 'created' | 'state_changed' | 'activity' | 'heartbeat' | 'terminal' | 'reconciliation' | 'diagnostic';
export type Capability = 'known' | 'unknown';
export interface Capabilities { readonly history: Capability; readonly heartbeat: Capability; readonly snapshot: Capability; readonly cancel: Capability; readonly terminalCause: Capability; }
export interface Lineage { readonly parentChildId?: string; readonly rootChildId: string; readonly attempt: number; readonly external: boolean; readonly adoptedAt?: string; }
export interface LifecycleEvent { readonly schemaVersion: 1; readonly eventId: string; readonly source: string; readonly sourceEpoch: string; readonly childId: string; readonly lineage: Lineage; readonly kind: LifecycleKind; readonly state?: ChildState; readonly observedAt: string; readonly sequence?: number; readonly activity?: string; readonly details?: Record<string, unknown>; readonly capabilities?: Capabilities; }
export interface ProgressSnapshot { readonly source: string; readonly childId: string; readonly state: ChildState; readonly observedAt: string; readonly lineage: Lineage; readonly capabilities: Capabilities; readonly lastSequence?: number; readonly lastActivity?: string; readonly lastHeartbeatAt?: string; readonly stale?: boolean; readonly gapDetected?: boolean; }
export interface Diagnostic { readonly code: string; readonly message: string; readonly offset?: number; readonly raw?: string; }
export interface ApplyResult { readonly status: 'applied' | 'provisional' | 'deduplicated' | 'out_of_order' | 'conflict' | 'stale' | 'terminal_immutable'; readonly record?: ProgressSnapshot; readonly diagnostics: readonly Diagnostic[]; }
export interface AuthoritativeSnapshot { readonly source: string; readonly sourceEpoch: string; readonly snapshotId: string; readonly observedAt: string; readonly complete: true; readonly coverage: 'all' | readonly string[]; readonly children: readonly { readonly childId: string; readonly state: ChildState; readonly sequence?: number; readonly details?: Record<string, unknown> }[]; }
export interface ReconcileResult { readonly audit: readonly { readonly source: string; readonly childId: string; readonly from: ChildState; readonly to: ChildState; readonly snapshotId: string; readonly reason: 'authoritative_snapshot' }[]; readonly diagnostics: readonly Diagnostic[]; }
const states = new Set<ChildState>(['created', 'starting', 'running', 'waiting', 'completed', 'failed', 'cancelled', 'lost']);
const terminal = new Set<ChildState>(['completed', 'failed', 'cancelled', 'lost']);
const kinds = new Set<LifecycleKind>(['created', 'state_changed', 'activity', 'heartbeat', 'terminal', 'reconciliation', 'diagnostic']);
const capabilities = new Set<Capability>(['known', 'unknown']);
const edges: Record<ChildState, readonly ChildState[]> = { created: ['starting', 'cancelled', 'failed', 'lost'], starting: ['running', 'waiting', 'cancelled', 'failed', 'lost'], running: ['waiting', 'completed', 'failed', 'cancelled', 'lost'], waiting: ['running', 'completed', 'failed', 'cancelled', 'lost'], completed: [], failed: [], cancelled: [], lost: [] };
const defaultCapabilities: Capabilities = { history: 'unknown', heartbeat: 'unknown', snapshot: 'unknown', cancel: 'unknown', terminalCause: 'unknown' };

export function normalizeLifecycleEvent(value: unknown): LifecycleEvent {
  if (!record(value)) throw new TypeError('Lifecycle event must be an object');
  if (value.schemaVersion !== 1) throw new TypeError('schemaVersion must be 1');
  const kind = text(value.kind, 'kind') as LifecycleKind; if (!kinds.has(kind)) throw new TypeError('Unsupported lifecycle kind');
  const state = value.state === undefined ? undefined : text(value.state, 'state') as ChildState;
  if ((kind === 'created' || kind === 'state_changed' || kind === 'terminal') !== (state !== undefined)) throw new TypeError(`${kind} state is required/forbidden`);
  if (state !== undefined && !states.has(state)) throw new TypeError('Unsupported child state');
  if (kind === 'created' && state !== 'created') throw new TypeError('created state must be created');
  if (kind === 'terminal' && !terminal.has(state!)) throw new TypeError('terminal must be terminal');
  const lineageValue = value.lineage; if (!record(lineageValue)) throw new TypeError('lineage is required');
  const lineage: Lineage = { rootChildId: text(lineageValue.rootChildId, 'lineage.rootChildId'), attempt: integer(lineageValue.attempt, 'lineage.attempt'), external: bool(lineageValue.external, 'lineage.external'), ...(lineageValue.parentChildId === undefined ? {} : { parentChildId: text(lineageValue.parentChildId, 'lineage.parentChildId') }), ...(lineageValue.adoptedAt === undefined ? {} : { adoptedAt: timestamp(lineageValue.adoptedAt, 'lineage.adoptedAt') }) };
  const c = value.capabilities === undefined ? defaultCapabilities : normalizeCapabilities(value.capabilities);
  const event: LifecycleEvent = { schemaVersion: 1, eventId: text(value.eventId, 'eventId'), source: text(value.source, 'source'), sourceEpoch: text(value.sourceEpoch, 'sourceEpoch'), childId: text(value.childId, 'childId'), lineage, kind, ...(state === undefined ? {} : { state }), observedAt: timestamp(value.observedAt, 'observedAt'), capabilities: c, ...(value.sequence === undefined ? {} : { sequence: integer(value.sequence, 'sequence') }), ...(value.activity === undefined ? {} : { activity: bounded(text(value.activity, 'activity')) }), ...(value.details === undefined ? {} : { details: sanitize(value.details) as Record<string, unknown> }) };
  return event;
}

export class LifecycleProjector {
  private readonly records = new Map<string, ProgressSnapshot>(); private readonly identities = new Map<string, string>(); private readonly highs = new Map<string, number>(); private readonly epochs = new Map<string, string>(); private readonly reconciling = new Map<string, number>();
  private readonly staleAfterMs: number; private readonly reconcileDeadlineMs: number;
  constructor(options: { staleAfterMs?: number; reconcileDeadlineMs?: number } = {}) { this.staleAfterMs = options.staleAfterMs ?? 120_000; this.reconcileDeadlineMs = options.reconcileDeadlineMs ?? 30_000; }
  apply(input: unknown): ApplyResult {
    const e = normalizeLifecycleEvent(input); const key = keyFor(e.source, e.childId); const epoch = this.epochs.get(key); if (epoch !== undefined && epoch !== e.sourceEpoch) return result('conflict', this.records.get(key), 'epoch_conflict'); const canonical = JSON.stringify(e); const identity = e.sequence === undefined ? `id\0${e.eventId}` : `seq\0${e.source}\0${e.sourceEpoch}\0${e.childId}\0${e.sequence}`;
    const prior = this.identities.get(identity); if (prior !== undefined) return prior === canonical ? result('deduplicated') : result('conflict', undefined, 'identity_conflict');
    const scope = `${e.source}\0${e.sourceEpoch}\0${e.childId}`; const high = this.highs.get(scope); if (e.sequence !== undefined && high !== undefined && e.sequence < high) return result('out_of_order', undefined, 'out_of_order');
    const current = this.records.get(key); if (current && terminal.has(current.state)) return result('terminal_immutable', current, 'terminal_immutable');
    if (!current && e.kind !== 'created') throw new Error('First accepted event must be created');
    if (current && e.kind === 'created') throw new Error('created must be first accepted event');
    if (e.kind === 'activity' || e.kind === 'heartbeat') {
      const next = { ...current!, observedAt: e.observedAt, ...(e.activity === undefined ? {} : { lastActivity: e.activity }), ...(e.kind === 'heartbeat' ? { lastHeartbeatAt: e.observedAt } : {}) }; this.records.set(key, next); this.epochs.set(key, e.sourceEpoch); this.identities.set(identity, canonical); if (e.sequence !== undefined) this.highs.set(scope, e.sequence); return result('applied', next);
    }
    if (current && !edges[current.state].includes(e.state!)) throw new Error(`Illegal transition ${current.state} -> ${e.state}`);
    const gap = e.sequence !== undefined && high !== undefined && e.sequence > high + 1; const next: ProgressSnapshot = { source: e.source, childId: e.childId, state: e.state!, observedAt: e.observedAt, lineage: e.lineage, capabilities: e.capabilities ?? defaultCapabilities, ...(e.sequence === undefined ? {} : { lastSequence: e.sequence }), ...(current?.lastActivity === undefined ? {} : { lastActivity: current.lastActivity }), ...(current?.lastHeartbeatAt === undefined ? {} : { lastHeartbeatAt: current.lastHeartbeatAt }), ...(gap ? { gapDetected: true } : {}) };
    this.records.set(key, next); this.epochs.set(key, e.sourceEpoch); this.identities.set(identity, canonical); if (e.sequence !== undefined) this.highs.set(scope, e.sequence); return result(gap ? 'provisional' : 'applied', next, gap ? 'sequence_gap' : undefined);
  }
  snapshot(source: string, childId: string): ProgressSnapshot | undefined { return this.records.get(keyFor(source, childId)); }
  reconcile(snapshot: AuthoritativeSnapshot): ReconcileResult {
    const checked = normalizeSnapshot(snapshot); const audit: ReconcileResult['audit'][number][] = []; const diagnostics: Diagnostic[] = [];
    for (const child of checked.children) { const key = keyFor(checked.source, child.childId); const current = this.records.get(key); if (!current) continue; if (this.epochs.get(key) !== checked.sourceEpoch) { diagnostics.push(diag('epoch_conflict')); continue; } if (terminal.has(current.state) && current.state !== child.state) { diagnostics.push(diag('terminal_immutable')); continue; } if (current.state !== child.state) { const next = { ...current, state: child.state, observedAt: checked.observedAt, ...(child.sequence === undefined ? {} : { lastSequence: child.sequence }), stale: false, gapDetected: false }; this.records.set(key, next); this.reconciling.delete(key); audit.push({ source: checked.source, childId: child.childId, from: current.state, to: child.state, snapshotId: checked.snapshotId, reason: 'authoritative_snapshot' }); } }
    return { audit, diagnostics };
  }
  markStale(now: string): ApplyResult[] { const at = Date.parse(timestamp(now, 'now')); const out: ApplyResult[] = []; for (const [key, current] of this.records) { const seen = Date.parse(current.lastHeartbeatAt ?? current.observedAt); if (!terminal.has(current.state) && !current.stale && at - seen >= this.staleAfterMs) { const next = { ...current, stale: true }; this.records.set(key, next); this.reconciling.set(key, at + this.reconcileDeadlineMs); out.push(result('stale', next)); } } return out; }
  reconciliationFailed(source: string, childId: string, now: string): ApplyResult { const key = keyFor(source, childId); const current = this.records.get(key); if (!current || terminal.has(current.state)) return result('terminal_immutable', current); const deadline = this.reconciling.get(key); if (deadline === undefined) return result('deduplicated', current); const at = Date.parse(timestamp(now, 'now')); if (at < deadline) return result('provisional', current, 'reconciliation_pending'); this.reconciling.delete(key); const e = eventForLost(current, this.epochs.get(key)!, timestamp(now, 'now')); return this.apply(e); }
}
function eventForLost(current: ProgressSnapshot, sourceEpoch: string, observedAt: string): LifecycleEvent { return { schemaVersion: 1, eventId: `lost:${current.source}:${current.childId}:${observedAt}`, source: current.source, sourceEpoch, childId: current.childId, lineage: current.lineage, kind: 'state_changed', state: 'lost', observedAt, capabilities: current.capabilities }; }

export class JsonlLifecycleParser { readonly records: LifecycleEvent[] = []; readonly diagnostics: Diagnostic[] = []; private buffer: Uint8Array<ArrayBufferLike> = new Uint8Array(); private offset = 0; private readonly max: number; private readonly redactor: RegExp;
  constructor(options: { maxLineBytes?: number; redact?: RegExp } = {}) { this.max = options.maxLineBytes ?? 64 * 1024; this.redactor = options.redact ?? /(?:api[_-]?key|authorization|cookie|password|secret|token)\S*/gi; }
  push(bytes: Uint8Array): void { this.buffer = concat(this.buffer, bytes); let i; while ((i = this.buffer.indexOf(10)) >= 0) { const line = this.buffer.slice(0, i); this.buffer = this.buffer.slice(i + 1); this.line(line, this.offset); this.offset += i + 1; } }
  end(): { readonly records: readonly LifecycleEvent[]; readonly diagnostics: readonly Diagnostic[] } { if (this.buffer.length) { this.add('truncated', this.offset, this.buffer); this.buffer = new Uint8Array(); } return { records: this.records, diagnostics: this.diagnostics }; }
  private line(line: Uint8Array, offset: number): void { if (!line.length) return; if (line.length > this.max) return this.add('oversize', offset, line); try { const parsed = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(line)); const normalized = normalizeLifecycleEvent(parsed); if (record(parsed) && parsed.journalSequence !== undefined) Object.assign(normalized, { journalSequence: parsed.journalSequence }); this.records.push(normalized); } catch { this.add('malformed', offset, line); } }
  private add(code: string, offset: number, raw: Uint8Array): void { if (this.diagnostics.length < 32) this.diagnostics.push({ code, message: `JSONL ${code}`, offset, raw: bounded(redactDiagnostic(new TextDecoder().decode(raw), this.redactor)) }); }
}
const writers = new Set<string>();
interface JournalLockOptions { readonly lockTimeoutMs?: number; readonly lockRetryMs?: number; readonly staleLockMs?: number; }
interface JournalLock { readonly token: string; readonly path: string; }
export class JsonlLifecycleJournal { private broken = false; private appendTail: Promise<void> = Promise.resolve(); private readonly path: string; private readonly lockTimeoutMs: number; private readonly lockRetryMs: number; private readonly staleLockMs: number;
  constructor(path: string, options: JournalLockOptions = {}) { this.path = path; this.lockTimeoutMs = options.lockTimeoutMs ?? 5_000; this.lockRetryMs = options.lockRetryMs ?? 10; this.staleLockMs = options.staleLockMs ?? 300_000; if (writers.has(path)) throw new Error('single writer journal only'); writers.add(path); }
  append(input: unknown): Promise<LifecycleEvent & { readonly journalSequence: number }> { const work = this.appendTail.then(() => this.appendOne(input)); this.appendTail = work.then(() => undefined, () => undefined); return work; }
  private async appendOne(input: unknown): Promise<LifecycleEvent & { readonly journalSequence: number }> { if (this.broken) throw new Error('journal integrity failure'); const lock = await this.acquireLock(); try { const replay = await this.replay(); if (replay.diagnostics.length) { this.broken = true; throw new Error('journal integrity failure'); } const event = normalizeLifecycleEvent(input); const entry = { ...event, journalSequence: replay.entries.length + 1 }; await appendFile(this.path, `${JSON.stringify(entry)}\n`); return entry; } finally { await this.releaseLock(lock); } }
  private async acquireLock(): Promise<JournalLock> { const path = `${this.path}.lock`; const token = randomUUID(); const deadline = Date.now() + this.lockTimeoutMs; for (;;) { try { await mkdir(path); try { await writeFile(`${path}/owner.json`, JSON.stringify({ pid: process.pid, token, createdAt: Date.now() })); } catch (error) { await rm(path, { recursive: true, force: true }); throw error; } return { path, token }; } catch (error: unknown) { if (!record(error) || error.code !== 'EEXIST') throw error; await this.reclaimStaleLock(path); if (Date.now() >= deadline) throw new Error('journal lock timeout'); await delay(this.lockRetryMs); } } }
  private async reclaimStaleLock(path: string): Promise<void> { let info: { mtimeMs: number }; try { info = await stat(path); } catch (error: unknown) { if (record(error) && error.code === 'ENOENT') return; throw error; } if (Date.now() - info.mtimeMs < this.staleLockMs) return; let owner: { pid?: unknown; token?: unknown } = {}; try { owner = JSON.parse(await readFile(`${path}/owner.json`, 'utf8')); } catch { return; } if (!integerOrUndefined(owner.pid) || processExists(owner.pid as number)) return; const tombstone = `${path}.stale-${randomUUID()}`; try { await rename(path, tombstone); await rm(tombstone, { recursive: true, force: true }); } catch (error: unknown) { if (!record(error) || error.code !== 'ENOENT') throw error; } }
  private async releaseLock(lock: JournalLock): Promise<void> { try { const owner = JSON.parse(await readFile(`${lock.path}/owner.json`, 'utf8')) as { token?: unknown }; if (owner.token === lock.token) await rm(lock.path, { recursive: true, force: true }); } catch (error: unknown) { if (!record(error) || error.code !== 'ENOENT') throw error; } }
  async replay(): Promise<{ readonly entries: readonly (LifecycleEvent & { readonly journalSequence: number })[]; readonly diagnostics: readonly Diagnostic[] }> { let raw: Uint8Array; try { raw = new Uint8Array(await readFile(this.path)); } catch (e: unknown) { if (record(e) && e.code === 'ENOENT') return { entries: [], diagnostics: [] }; throw e; } const p = new JsonlLifecycleParser(); p.push(raw); const done = p.end(); const entries: (LifecycleEvent & { readonly journalSequence: number })[] = []; const diagnostics = [...done.diagnostics]; for (const [index, value] of done.records.entries()) { const candidate = value as LifecycleEvent & { journalSequence?: unknown }; if (integerOrUndefined(candidate.journalSequence) !== index + 1) diagnostics.push(diag('journal_sequence')); else entries.push({ ...value, journalSequence: candidate.journalSequence as number }); } return { entries, diagnostics }; }
}
function processExists(pid: number): boolean { try { process.kill(pid, 0); return true; } catch (error: unknown) { return record(error) && error.code === 'EPERM'; } }
function delay(ms: number): Promise<void> { return new Promise(resolve => setTimeout(resolve, ms)); }
function result(status: ApplyResult['status'], record?: ProgressSnapshot, code?: string): ApplyResult { return { status, ...(record === undefined ? {} : { record }), diagnostics: code === undefined ? [] : [diag(code)] }; } function diag(code: string): Diagnostic { return { code, message: code }; }
function normalizeSnapshot(value: unknown): AuthoritativeSnapshot { if (!record(value)) throw new TypeError('snapshot must be an object'); if (value.complete !== true) throw new TypeError('snapshot must be complete'); const source = text(value.source, 'source'); const sourceEpoch = text(value.sourceEpoch, 'sourceEpoch'); const snapshotId = text(value.snapshotId, 'snapshotId'); const observedAt = timestamp(value.observedAt, 'observedAt'); const coverage = value.coverage === 'all' ? 'all' : Array.isArray(value.coverage) && value.coverage.length > 0 ? value.coverage.map((x, i) => text(x, `coverage[${i}]`)) : (() => { throw new TypeError('coverage must be all or a non-empty child list'); })(); if (!Array.isArray(value.children)) throw new TypeError('children must be an array'); const children = value.children.map((child, i) => { if (!record(child)) throw new TypeError(`children[${i}] must be an object`); const state = text(child.state, `children[${i}].state`) as ChildState; if (!states.has(state)) throw new TypeError('Unsupported child state'); return { childId: text(child.childId, `children[${i}].childId`), state, ...(child.sequence === undefined ? {} : { sequence: integer(child.sequence, `children[${i}].sequence`) }), ...(child.details === undefined ? {} : { details: sanitize(child.details) as Record<string, unknown> }) }; }); const childIds = new Set(children.map(child => child.childId)); if (coverage !== 'all' && (coverage.length !== childIds.size || coverage.some(id => !childIds.has(id)))) throw new TypeError('coverage must exactly name snapshot children'); return { source, sourceEpoch, snapshotId, observedAt, complete: true, coverage, children }; }
function normalizeCapabilities(value: unknown): Capabilities { if (!record(value)) throw new TypeError('capabilities required'); const out = {} as Record<keyof Capabilities, Capability>; for (const k of Object.keys(defaultCapabilities) as (keyof Capabilities)[]) { if (!capabilities.has(value[k] as Capability)) throw new TypeError('capabilities must be known or unknown'); out[k] = value[k] as Capability; } return out as Capabilities; }
function text(v: unknown, n: string): string { if (typeof v !== 'string' || !v.trim()) throw new TypeError(`${n} is required`); return v.trim(); } function integer(v: unknown, n: string): number { if (!Number.isSafeInteger(v) || (v as number) < 0) throw new TypeError(`${n} must be a non-negative integer`); return v as number; } function integerOrUndefined(v: unknown): number | undefined { return Number.isSafeInteger(v) && (v as number) >= 0 ? v as number : undefined; } function bool(v: unknown, n: string): boolean { if (typeof v !== 'boolean') throw new TypeError(`${n} must be boolean`); return v; } function timestamp(v: unknown, n: string): string { const s = text(v, n); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(s) || Number.isNaN(Date.parse(s))) throw new TypeError(`${n} must be RFC3339 UTC`); return s; } function keyFor(s: string, c: string): string { return `${s}\0${c}`; } function record(v: unknown): v is Record<string, unknown> { return typeof v === 'object' && v !== null && !Array.isArray(v); } function bounded(s: string): string { return s.slice(0, 512); } function redactDiagnostic(raw: string, redactor: RegExp): string { try { return JSON.stringify(redactJson(JSON.parse(raw))); } catch { return raw.replace(redactor, '[REDACTED]'); } } function redactJson(v: unknown): unknown { if (Array.isArray(v)) return v.map(redactJson); if (record(v)) return Object.fromEntries(Object.entries(v).map(([k, x]) => /secret|token|password|authorization|cookie|api[_-]?key/i.test(k) ? [k, '[REDACTED]'] : [k, redactJson(x)])); return v; } function sanitize(v: unknown): unknown { if (Array.isArray(v)) return v.map(sanitize); if (record(v)) return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, /secret|token|password|authorization|cookie/i.test(k) ? '[REDACTED]' : sanitize(x)])); if (v === null || ['string', 'number', 'boolean'].includes(typeof v)) return v; throw new TypeError('details must be JSON serializable'); } function concat(a: Uint8Array<ArrayBufferLike>, b: Uint8Array<ArrayBufferLike>): Uint8Array<ArrayBufferLike> { const x = new Uint8Array(a.length + b.length); x.set(a); x.set(b, a.length); return x; }
