#!/usr/bin/env node
/**
 * THE PROFILE, THE FINGERPRINT, AND THE FILE EVERY SESSION LOADS.
 *
 * `skills-lock.json` says what is INSTALLED and is rewritten by the Skills CLI, so nothing this
 * skill needs may live in it. `skills-profile.json` says what this project USES, why, and when —
 * beside the lock file, in the same repository, so a teammate's checkout carries the same answer.
 *
 * `.claude/rules/skill-routing.md` is the half that does the work. A rules file with no `paths`
 * frontmatter loads at the start of every session at the same priority as the project CLAUDE.md,
 * which is the only supported way to put a skill in front of an agent that did not think to look
 * for it. It is GENERATED: the evidence stays in the profile so the always-loaded text is one
 * line per skill, and rendering is deterministic so the check can tell a hand edit from a drift.
 *
 * WHAT IS NEVER COMMITTED: the placement answer for a repository kept local, and the user's own
 * config, both under the user's agents directory. Committed evidence holds counts and
 * repository-relative paths only — never an absolute path, a file's contents, or history text.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

export const PROFILE_VERSION = 1;
export const PROFILE_FILE = 'skills-profile.json';
export const RULES_RELATIVE = join('.claude', 'rules', 'skill-routing.md');
export const RULES_HEADER = '<!-- Generated by onboard-project from skills-profile.json. Do not edit; change the profile and run refresh. -->';

/** Strong first, then weak, then general: the order the routing file lists them in. */
const MATCH_ORDER = { strong: 0, weak: 1, general: 2 };

/** The way Claude Code names a project directory, reused so a profile path is predictable. */
function encodePath(repoRoot) {
  return resolve(repoRoot).replace(/[^A-Za-z0-9]/g, '-');
}

export function localProfilePath(repoRoot, { home = homedir() } = {}) {
  return join(home, '.agents', 'project-profiles', `${encodePath(repoRoot)}.json`);
}

export function profilePaths(repoRoot, { home = homedir() } = {}) {
  return { committed: join(resolve(repoRoot), PROFILE_FILE), local: localProfilePath(repoRoot, { home }) };
}

export function rulesPath(repoRoot) {
  return join(resolve(repoRoot), RULES_RELATIVE);
}

export function userConfigPath({ home = homedir() } = {}) {
  return join(home, '.agents', 'onboard-project.json');
}

/** The user's own answers: which origin owners take committed files. Absent is an empty list. */
export function userConfig({ home = homedir() } = {}) {
  try {
    const parsed = JSON.parse(readFileSync(userConfigPath({ home }), 'utf8'));
    return { ...parsed, commitOwners: Array.isArray(parsed?.commitOwners) ? parsed.commitOwners : [] };
  } catch {
    return { commitOwners: [] };
  }
}

function readJson(path) {
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8'));
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
  } catch {
    return null; // absent, unreadable, or hand-edited into nonsense
  }
}

/** The committed profile if there is one, else the local one. Corruption reads as absent. */
export function readProfile(repoRoot, { home = homedir() } = {}) {
  const paths = profilePaths(repoRoot, { home });
  return readJson(paths.committed) ?? readJson(paths.local);
}

/** Temporary file, then rename: two sessions refreshing at once cannot leave half a file. */
export function writeJsonAtomically(path, value) {
  const temporary = `${path}.${process.pid}.tmp`;
  try {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(temporary, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
    renameSync(temporary, path);
    return true;
  } catch {
    try {
      unlinkSync(temporary);
    } catch {
      // nothing to clean up
    }
    return false;
  }
}

export function writeTextAtomically(path, text) {
  const temporary = `${path}.${process.pid}.tmp`;
  try {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(temporary, text);
    renameSync(temporary, path);
    return true;
  } catch {
    try {
      unlinkSync(temporary);
    } catch {
      // nothing to clean up
    }
    return false;
  }
}

/** Writes to the location the profile's own `placement` names. */
export function writeProfile(repoRoot, profile, { home = homedir() } = {}) {
  const paths = profilePaths(repoRoot, { home });
  return writeJsonAtomically(profile.placement === 'local' ? paths.local : paths.committed, profile);
}

/**
 * The fingerprint of what the repository currently says.
 *
 * Built from the stable ids of the signals that evaluated true, sorted, with the skill name
 * attached so the same signals under a different skill cannot collide. REPO SIGNALS ONLY: the
 * session-start check never reads history, and a fingerprint it cannot recompute is a fingerprint
 * that reports drift every time.
 */
export function fingerprintOf(trueSignalsBySkill) {
  const rows = [];
  for (const [skill, signals] of Object.entries(trueSignalsBySkill ?? {})) {
    for (const signal of [...new Set(signals ?? [])]) rows.push(`${skill} ${signal}`);
  }
  rows.sort();
  return createHash('sha256').update(rows.join('\n')).digest('hex');
}

/** The always-loaded file: a header saying it is generated, then one line per skill. */
export function renderRules(profile) {
  const entries = Object.entries(profile?.skills ?? {})
    .filter(([, entry]) => entry?.useWhen)
    .sort((left, right) => {
      const order = (MATCH_ORDER[left[1].match] ?? 3) - (MATCH_ORDER[right[1].match] ?? 3);
      return order !== 0 ? order : left[0].localeCompare(right[0]);
    });
  const lines = [
    RULES_HEADER,
    '# Skill routing for this project',
    '',
    'These skills were chosen from evidence in this repository. Load one when the moment matches;',
    'nothing here is enforced.',
    '',
    ...entries.map(([name, entry]) => `- ${entry.useWhen} → \`${name}\``),
  ];
  return `${lines.join('\n')}\n`;
}

/** True when the rules file on disk is not what this profile would render. */
export function rulesDrifted(repoRoot, profile) {
  const path = rulesPath(repoRoot);
  if (!existsSync(path)) return true;
  try {
    return readFileSync(path, 'utf8') !== renderRules(profile);
  } catch {
    return true;
  }
}

function lockSkills(path) {
  const parsed = readJson(path);
  const skills = parsed?.skills;
  return skills && typeof skills === 'object' ? Object.keys(skills) : [];
}

function directorySkills(directory) {
  try {
    return readdirSync(directory, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && existsSync(join(directory, entry.name, 'SKILL.md')))
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

/**
 * Every skill this machine can load for this repository, and the scope it came from.
 *
 * Both lock files and both skill directories, because an installation can be recorded in a lock,
 * present only as a directory, or both — and the check must not report a skill missing that the
 * session will happily load.
 */
export function installedSkills({ repoRoot, home = homedir() } = {}) {
  const found = new Map();
  const add = (name, scope) => {
    if (!found.has(name)) found.set(name, scope);
  };
  if (repoRoot) {
    const root = resolve(repoRoot);
    for (const name of lockSkills(join(root, 'skills-lock.json'))) add(name, 'project');
    for (const directory of [join(root, '.agents', 'skills'), join(root, '.claude', 'skills')]) {
      for (const name of directorySkills(directory)) add(name, 'project');
    }
  }
  for (const name of lockSkills(join(home, '.agents', '.skill-lock.json'))) add(name, 'global');
  for (const directory of [join(home, '.agents', 'skills'), join(home, '.claude', 'skills')]) {
    for (const name of directorySkills(directory)) add(name, 'global');
  }
  return found;
}
