#!/usr/bin/env node
/**
 * THE PROFILE, THE FINGERPRINT, AND THE FILE EVERY SESSION LOADS.
 *
 * `skills-lock.json` says what is INSTALLED and is rewritten by the Skills CLI, so nothing this
 * skill needs may live in it. `skills-profile.json` says what this project USES, why, and when —
 * beside the lock file, in the same repository, so a teammate's checkout carries the same answer.
 *
 * `.claude/rules/skill-routing.md` is the half that does the work. A rules file with no `paths`
 * frontmatter loads at the start of every session at the same priority as the project CLAUDE.md,
 * which is the only supported way to put a skill in front of an agent that did not think to look
 * for it. It is GENERATED: the evidence stays in the profile so the always-loaded text is one
 * line per skill, and rendering is deterministic so the check can tell a hand edit from a drift.
 *
 * WHAT IS NEVER COMMITTED: the placement answer for a repository kept local, and the user's own
 * config, both under the user's agents directory. Committed evidence holds counts and
 * repository-relative paths only — never an absolute path, a file's contents, or history text.
 *
 * AN ADAPTED COPY STANDS IN FOR THE SKILL IT ADAPTS. `update-agent-skills` composes a project's
 * adapted copy of a pack skill under a name of its own, and its `adapted.lock.json` names the skill
 * it adapts. Before this was read, a repository that had adapted `release-notes` was still told to
 * install `release-notes`, the check called it missing at every session start, and the routing sent
 * the session to the generic copy, which carries none of the project's values. The profile's
 * `adapted` map records every such copy, and the routing names the copy rather than the skill.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

export const PROFILE_VERSION = 1;
export const PROFILE_FILE = 'skills-profile.json';
export const RULES_RELATIVE = join('.claude', 'rules', 'skill-routing.md');
export const RULES_HEADER = '<!-- Generated by onboard-project from skills-profile.json. Do not edit; change the profile and run refresh. -->';

/**
 * Strong first, then adapted, then weak, then general: the order the routing file lists them in.
 * `adapted` sits between two kinds that already existed, so every profile written before it renders
 * in the same order, and its committed routing file does not read as drift.
 */
const MATCH_ORDER = { strong: 0, adapted: 1, weak: 2, general: 3 };
const UNKNOWN_MATCH = 4;

/** The file `update-agent-skills` writes beside every adapted copy it composes. */
export const ADAPTED_LOCK_FILE = 'adapted.lock.json';

/** Where a repository's own skills are loaded from, and so where an adapted copy can sit. */
const PROJECT_SKILL_DIRECTORIES = [join('.claude', 'skills'), join('.agents', 'skills')];

// What a lock has to hold for its copy to stand in for a skill. Each value is written into the
// routing file, which every session loads, so each has to be one plain token.
const SKILL_NAME = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const REF = /^[A-Za-z0-9._/+-]{1,255}$/;
const TREE = /^(?:[0-9a-f]{40}|[0-9a-f]{64})$/;
const ENTRY = /^(?![/.])(?!.*(?:^|\/)\.\.?(?:\/|$))[A-Za-z0-9._/-]{1,255}\.md$/;
const ENTRY_DEFAULT = 'SKILL.md';

/** Plain code-point order: nothing this skill writes may depend on the machine's locale. */
function byCodePoint(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** The way Claude Code names a project directory: readable, and not unique on its own. */
function encodePath(repoRoot) {
  return resolve(repoRoot).replace(/[^A-Za-z0-9]/g, '-');
}

/**
 * Where a repository kept local keeps its profile.
 *
 * The readable part is Claude Code's own project-directory encoding, and it COLLIDES: every
 * character that is not a letter or a digit becomes `-`, so `work/foo-bar` and `work/foo/bar` are
 * one name, and so are `my-app` and `my_app`. In 0.22.0 that name was the whole file name, so two
 * repositories shared one profile — one's apply overwrote the other's, and the other's session-start
 * check reported the first one's skills as missing. A short hash of the full path now follows it.
 */
export function localProfilePath(repoRoot, { home = homedir() } = {}) {
  const resolved = resolve(repoRoot);
  const digest = createHash('sha256').update(resolved).digest('hex').slice(0, 12);
  return join(home, '.agents', 'project-profiles', `${encodePath(resolved).slice(0, 160)}-${digest}.json`);
}

/**
 * The 0.22.0 name. Exported so the collision can be tested and documented, and NEVER READ: a file
 * at this name carries no \`repo\` field, so nothing can tell which of the repositories that share the
 * name wrote it — and reading it would copy one repository's skills into another's profile, where a
 * refresh now keeps them. A repository onboarded locally with 0.22.0 is simply onboarded again.
 */
export function legacyLocalProfilePath(repoRoot, { home = homedir() } = {}) {
  return join(home, '.agents', 'project-profiles', `${encodePath(repoRoot)}.json`);
}

export function profilePaths(repoRoot, { home = homedir() } = {}) {
  return { committed: join(resolve(repoRoot), PROFILE_FILE), local: localProfilePath(repoRoot, { home }) };
}

export function rulesPath(repoRoot) {
  return join(resolve(repoRoot), RULES_RELATIVE);
}

export function userConfigPath({ home = homedir() } = {}) {
  return join(home, '.agents', 'onboard-project.json');
}

/** The user's own answers: which origin owners take committed files. Absent is an empty list. */
export function userConfig({ home = homedir() } = {}) {
  try {
    const parsed = JSON.parse(readFileSync(userConfigPath({ home }), 'utf8'));
    return { ...parsed, commitOwners: Array.isArray(parsed?.commitOwners) ? parsed.commitOwners : [] };
  } catch {
    return { commitOwners: [] };
  }
}

function readJson(path) {
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8'));
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
  } catch {
    return null; // absent, unreadable, or hand-edited into nonsense
  }
}

/** A profile has a skill list. Anything else at a profile's path — the check's one-time
 *  suggestion marker, above all — is not one, and reading it as one is how 0.22.0's plan came to
 *  claim a placement had been "recorded" for a repository that had never been onboarded. */
function isProfile(record) {
  return Boolean(record && record.skills && typeof record.skills === 'object' && !Array.isArray(record.skills));
}

/**
 * This repository's record under the user's agents directory. It must name this repository: a
 * record that names another, or none at all, is refused, because a collision has to read as
 * "nothing here" rather than as somebody else's profile.
 */
function readLocalRecord(repoRoot, { home }) {
  const resolved = resolve(repoRoot);
  const record = readJson(localProfilePath(resolved, { home }));
  return record && record.repo === resolved ? record : null;
}

/** The committed profile if there is one, else the local one. Corruption and markers read as absent. */
export function readProfile(repoRoot, { home = homedir() } = {}) {
  const committed = readJson(profilePaths(repoRoot, { home }).committed);
  if (isProfile(committed)) return committed;
  const local = readLocalRecord(repoRoot, { home });
  return isProfile(local) ? local : null;
}

/** The check's note that it has already suggested onboarding here, or null. */
export function readSuggestionMarker(repoRoot, { home = homedir() } = {}) {
  const local = readLocalRecord(repoRoot, { home });
  return local && !isProfile(local) && local.onboarding ? local : null;
}

export function writeSuggestionMarker(repoRoot, { home = homedir() } = {}) {
  const resolved = resolve(repoRoot);
  return writeJsonAtomically(localProfilePath(resolved, { home }), {
    version: PROFILE_VERSION,
    onboarding: 'suggested',
    at: new Date().toISOString(),
    repo: resolved,
  });
}

/** Temporary file, then rename: two sessions refreshing at once cannot leave half a file. */
export function writeJsonAtomically(path, value) {
  const temporary = `${path}.${process.pid}.tmp`;
  try {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(temporary, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
    renameSync(temporary, path);
    return true;
  } catch {
    try {
      unlinkSync(temporary);
    } catch {
      // nothing to clean up
    }
    return false;
  }
}

export function writeTextAtomically(path, text) {
  const temporary = `${path}.${process.pid}.tmp`;
  try {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(temporary, text);
    renameSync(temporary, path);
    return true;
  } catch {
    try {
      unlinkSync(temporary);
    } catch {
      // nothing to clean up
    }
    return false;
  }
}

/**
 * Writes to the location the profile's own `placement` names.
 *
 * A local profile records the repository it belongs to, so a reader can refuse one that is not its
 * own. A committed profile never does: it is published with the repository, and an absolute path
 * from one machine has no business in a file every clone carries.
 */
export function writeProfile(repoRoot, profile, { home = homedir() } = {}) {
  const resolved = resolve(repoRoot);
  const { repo: _ignored, ...rest } = profile;
  if (profile.placement === 'local') {
    return writeJsonAtomically(localProfilePath(resolved, { home }), { ...rest, repo: resolved });
  }
  return writeJsonAtomically(profilePaths(resolved, { home }).committed, rest);
}

/**
 * The fingerprint of what the repository currently says.
 *
 * Built from the stable ids of the signals that evaluated true, sorted, with the skill name
 * attached so the same signals under a different skill cannot collide. REPO SIGNALS ONLY: the
 * session-start check never reads history, and a fingerprint it cannot recompute is a fingerprint
 * that reports drift every time.
 */
export function fingerprintOf(trueSignalsBySkill) {
  const rows = [];
  for (const [skill, signals] of Object.entries(trueSignalsBySkill ?? {})) {
    for (const signal of [...new Set(signals ?? [])]) rows.push(`${skill} ${signal}`);
  }
  rows.sort();
  return createHash('sha256').update(rows.join('\n')).digest('hex');
}

/**
 * Why a lock cannot stand in for a skill, or null when it can. The composer's own check holds the
 * copy to its lock; this asks only whether the lock names a skill, a pin and a tree that can be
 * written into a profile and a routing file.
 */
function adaptedLockProblem(lock, folder) {
  // The routing file and the profile name the copy by its folder, and a folder that is not a skill
  // name would be counted here and then dropped when the profile is recorded: present to the plan
  // and the check, and reported as changed at every session start after.
  if (!SKILL_NAME.test(folder)) return 'the folder name is not a skill name (lowercase letters, digits and single hyphens)';
  if (!lock) return `${ADAPTED_LOCK_FILE} does not read as a JSON object`;
  if (lock.version !== 1) return `${ADAPTED_LOCK_FILE} has version ${JSON.stringify(lock.version ?? null)}, which this skill does not read: if a newer composer wrote it, update onboard-project`;
  if (lock.name !== undefined && lock.name !== folder) return `${ADAPTED_LOCK_FILE} names ${JSON.stringify(lock.name)}, not its own folder`;
  const base = lock.base;
  if (!base || typeof base !== 'object' || Array.isArray(base)) return `${ADAPTED_LOCK_FILE} names no skill it adapts`;
  if (typeof base.skill !== 'string' || !SKILL_NAME.test(base.skill)) return `${ADAPTED_LOCK_FILE} names no skill it adapts`;
  if (base.skill === folder) return `the copy takes the name of the skill it adapts, ${base.skill}`;
  if (typeof base.ref !== 'string' || !REF.test(base.ref)) return `${ADAPTED_LOCK_FILE} records no ref`;
  if (typeof base.tree !== 'string' || !TREE.test(base.tree)) return `${ADAPTED_LOCK_FILE} records no tree`;
  if (base.entry !== undefined && (typeof base.entry !== 'string' || !ENTRY.test(base.entry))) return `${ADAPTED_LOCK_FILE} records an entry that is not a Markdown file of the skill`;
  return null;
}

/**
 * Every adapted copy this repository holds, by the pack skill it adapts.
 *
 * A copy is a folder in one of the repository's own skill directories whose `adapted.lock.json`
 * (written by `update-agent-skills`' composer) names the skill it adapts, the file of that skill it
 * adapts (its `entry`), and the pin: the ref and the skill folder's git tree. Only the repository's
 * own directories are read, because an adapted copy is the project's and is committed with it.
 *
 * A copy that stands in for nothing is named in `ignored`, with why: a lock that cannot be read,
 * because a folder that merely looks adapted must never silence the report of a skill that is
 * missing; or a second folder of one name whose lock says something else, because a session loads
 * only one of the two. It reads a few small files and no history, so the session-start check can
 * afford it.
 */
export function adaptedCopies(repoRoot) {
  const root = resolve(repoRoot);
  const byBase = new Map();
  const ignored = [];
  const named = new Map();
  for (const directory of PROJECT_SKILL_DIRECTORIES) {
    let entries;
    try {
      entries = readdirSync(join(root, directory), { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries.filter((item) => item.isDirectory()).sort((left, right) => byCodePoint(left.name, right.name))) {
      const lockPath = join(root, directory, entry.name, ADAPTED_LOCK_FILE);
      if (!existsSync(lockPath)) continue;
      const where = `${directory.split('\\').join('/')}/${entry.name}`;
      const lock = readJson(lockPath);
      const problem = adaptedLockProblem(lock, entry.name);
      if (problem) {
        ignored.push(`${where}: ${problem}`);
        continue;
      }
      const copy = { name: entry.name, entry: lock.base.entry ?? ENTRY_DEFAULT, ref: lock.base.ref, tree: lock.base.tree };
      // One name, one skill: a session loads one of two folders that share a name, so only the
      // first is counted, in the order the directories are listed above. The same copy in both
      // places says nothing; a second one that adapts something else, or at another pin, is named.
      const first = named.get(entry.name);
      if (first) {
        const same = first.skill === lock.base.skill && ['entry', 'ref', 'tree'].every((key) => first.copy[key] === copy[key]);
        if (!same) ignored.push(`${where}: has the name of ${first.where}, which is read first, and its lock says something else`);
        continue;
      }
      named.set(entry.name, { where, skill: lock.base.skill, copy });
      if (!byBase.has(lock.base.skill)) byBase.set(lock.base.skill, []);
      byBase.get(lock.base.skill).push(copy);
    }
  }
  for (const copies of byBase.values()) copies.sort((left, right) => byCodePoint(left.name, right.name));
  return { byBase: new Map([...byBase].sort((left, right) => byCodePoint(left[0], right[0]))), ignored };
}

/** The `adapted` map a profile records: a plain object, keyed by the skill each copy adapts. */
export function adaptedRecord(byBase) {
  return Object.fromEntries([...(byBase ?? new Map())].map(([base, copies]) => [base, copies.map((copy) => ({ ...copy }))]));
}

/**
 * The copies a profile's `adapted` map lists for one skill, held to the shape a copy has. A profile
 * on disk can have been edited by hand, and nothing from it reaches the routing file unchecked.
 */
function recordedCopies(adapted, base) {
  if (!adapted || typeof adapted !== 'object' || Array.isArray(adapted)) return [];
  const listed = adapted[base];
  if (!Array.isArray(listed)) return [];
  return listed
    .filter((copy) => copy && typeof copy.name === 'string' && SKILL_NAME.test(copy.name))
    .map((copy) => ({
      name: copy.name,
      entry: typeof copy.entry === 'string' && ENTRY.test(copy.entry) ? copy.entry : ENTRY_DEFAULT,
      ref: typeof copy.ref === 'string' ? copy.ref : null,
      tree: typeof copy.tree === 'string' ? copy.tree : null,
    }))
    .sort((left, right) => byCodePoint(left.name, right.name));
}

/**
 * The adapted copies that differ between a profile and the repository: added, removed, moved to
 * another skill or entry, or re-pinned. Every copy the repository holds is compared, whether or not
 * this catalogue carries the skill it adapts, so an update to the catalogue never reads as this
 * repository changing. A profile written before adapted copies were read has no map, and reads as
 * one that recorded none.
 */
export function changedAdaptedCopies(recorded, byBase) {
  const identity = (base, copy) => [base, copy.entry, copy.ref, copy.tree].join('\n');
  const before = new Map();
  if (recorded && typeof recorded === 'object' && !Array.isArray(recorded)) {
    for (const base of Object.keys(recorded)) {
      for (const copy of recordedCopies(recorded, base)) before.set(copy.name, identity(base, copy));
    }
  }
  const now = new Map();
  for (const [base, copies] of byBase ?? new Map()) {
    for (const copy of copies) now.set(copy.name, identity(base, copy));
  }
  const changed = new Set();
  for (const [name, value] of before) if (now.get(name) !== value) changed.add(name);
  for (const [name, value] of now) if (before.get(name) !== value) changed.add(name);
  return [...changed].sort(byCodePoint);
}

/** Where the routing sends a task: the skill, or the copies this repository adapted from it. */
function routeTo(name, adapted) {
  const copies = recordedCopies(adapted, name);
  if (copies.length === 0) return `\`${name}\``;
  const labels = copies.map((copy) => (copy.entry === ENTRY_DEFAULT ? `\`${copy.name}\`` : `\`${copy.name}\` (from ${copy.entry})`));
  return `${labels.join(' or ')}, this repository's adapted ${copies.length === 1 ? 'copy' : 'copies'} of \`${name}\``;
}

/**
 * The always-loaded file: a header saying it is generated, then one line per skill.
 *
 * A skill this repository has adapted is routed to the adapted copy by name. The session then does
 * not depend on finding the copy by a description that a long skill listing may drop, nor on
 * passing over a generic copy installed beside it. A profile with no adapted copy renders exactly as
 * it did before adapted copies were read, so upgrading this skill never shows a committed routing
 * file as drift.
 */
export function renderRules(profile) {
  const adapted = profile?.adapted;
  const entries = Object.entries(profile?.skills ?? {})
    .filter(([, entry]) => entry?.useWhen)
    .sort((left, right) => {
      const order = (MATCH_ORDER[left[1].match] ?? UNKNOWN_MATCH) - (MATCH_ORDER[right[1].match] ?? UNKNOWN_MATCH);
      // Code-point order, never localeCompare: the file is compared byte for byte, and a collation
      // that depends on the machine's locale made two machines render one profile two ways — each
      // then reporting the other's committed file as drift at every session start.
      if (order !== 0) return order;
      return byCodePoint(left[0], right[0]);
    });
  const routesToCopy = entries.some(([name]) => recordedCopies(adapted, name).length > 0);
  const lines = [
    RULES_HEADER,
    '# Skill routing for this project',
    '',
    'These skills were chosen from evidence in this repository. Load one when the moment matches;',
    'nothing here is enforced.',
    ...(routesToCopy
      ? [
        '',
        'Where a line names an adapted copy, load that copy rather than the skill it adapts: it carries',
        "the skill's text, or only the file named after \"from\", together with this repository's values.",
        'Where a line names more than one copy, load the one whose own description fits the task.',
      ]
      : []),
    '',
    ...entries.map(([name, entry]) => `- ${entry.useWhen} → ${routeTo(name, adapted)}`),
  ];
  return `${lines.join('\n')}\n`;
}

/** True when the rules file on disk is not what this profile would render. */
export function rulesDrifted(repoRoot, profile) {
  const path = rulesPath(repoRoot);
  if (!existsSync(path)) return true;
  try {
    return readFileSync(path, 'utf8') !== renderRules(profile);
  } catch {
    return true;
  }
}

function lockSkills(path) {
  const parsed = readJson(path);
  const skills = parsed?.skills;
  return skills && typeof skills === 'object' ? Object.keys(skills) : [];
}

function directorySkills(directory) {
  try {
    return readdirSync(directory, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && existsSync(join(directory, entry.name, 'SKILL.md')))
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

/**
 * Every skill this machine can load for this repository, and the scope it came from.
 *
 * Both lock files and both skill directories, because an installation can be recorded in a lock,
 * present only as a directory, or both — and the check must not report a skill missing that the
 * session will happily load.
 */
export function installedSkills({ repoRoot, home = homedir() } = {}) {
  const found = new Map();
  const add = (name, scope) => {
    if (!found.has(name)) found.set(name, scope);
  };
  if (repoRoot) {
    const root = resolve(repoRoot);
    for (const name of lockSkills(join(root, 'skills-lock.json'))) add(name, 'project');
    for (const directory of [join(root, '.agents', 'skills'), join(root, '.claude', 'skills')]) {
      for (const name of directorySkills(directory)) add(name, 'project');
    }
  }
  for (const name of lockSkills(join(home, '.agents', '.skill-lock.json'))) add(name, 'global');
  for (const directory of [join(home, '.agents', 'skills'), join(home, '.claude', 'skills')]) {
    for (const name of directorySkills(directory)) add(name, 'global');
  }
  return found;
}
