#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { constants } from "node:fs";
import { access, chmod, copyFile, lstat, link, mkdir, mkdtemp, readFile, readdir, realpath, rename, rm, rmdir, stat, unlink, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";

const PACKAGE = "@crissmoldovan/workspace-governance";
const RECEIPT = "manager-receipt.json";
const REPOSITORY = "https://github.com/crissmoldovan/agent-skills";
const RELEASE_TAG = "workspace-governance-v0.3.0";
const MANIFEST_ASSET = "runtime-manifest.json";
const CATALOG_VERSION = "0.26.0";
const BINS = ["workspacectl", "workspacectl-mcp"];
const BIN_ENTRIES = { workspacectl: "dist/cli.js", "workspacectl-mcp": "dist/mcp-cli.js" };
class Refusal extends Error { constructor(code, message) { super(message); this.code = code; } }
const fail = (code, message) => { throw new Refusal(code, message); };
const sha = bytes => createHash("sha256").update(bytes).digest("hex");
const jsonBytes = value => Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
function inside(parent, target) { const r = relative(parent, target); return r === "" || (!r.startsWith(`..${sep}`) && r !== ".." && !isAbsolute(r)); }
async function kind(path) { try { const s = await lstat(path); return s.isSymbolicLink() ? "symlink" : s.isFile() ? "file" : s.isDirectory() ? "directory" : "other"; } catch (e) { if (e?.code === "ENOENT") return "absent"; throw e; } }
async function refuseSymlinkAncestors(path) { let cursor = resolve(path), parts = []; while (cursor !== dirname(cursor)) { parts.push(cursor); cursor = dirname(cursor); } for (const candidate of parts.reverse()) if (await kind(candidate) === "symlink") fail("CONFLICT", `selected path has a symlinked ancestor: ${candidate}`); }
function run(command, args, options = {}) { const r = spawnSync(command, args, { encoding: "utf8", maxBuffer: 128 * 1024 * 1024, ...options }); if (r.error || r.status !== 0) fail("UNAVAILABLE", `${basename(command)} failed: ${r.error?.message ?? r.stderr ?? r.stdout}`.trim()); return r.stdout; }
function parse(argv) {
  const action = argv.shift();
  if (!["status", "plan", "install", "update", "rollback", "remove"].includes(action)) fail("INVALID_ARGUMENT", "action must be status, plan, install, update, rollback, or remove");
  const o = { action, yes: false, json: false };
  while (argv.length) { const flag = argv.shift(); if (flag === "--yes") o.yes = true; else if (flag === "--json") o.json = true; else { const value = argv.shift(); if (!value || !["--bundle", "--manifest-sha256", "--root", "--bin-dir", "--version", "--preserve-version"].includes(flag)) fail("INVALID_ARGUMENT", `invalid argument ${flag}`); if (o[flag.slice(2).replaceAll("-", "_")] !== undefined) fail("INVALID_ARGUMENT", `duplicate ${flag}`); o[flag.slice(2).replaceAll("-", "_")] = value; } }
  for (const key of ["root", "bin_dir"]) if (!o[key] || !isAbsolute(o[key])) fail("INVALID_ARGUMENT", `--${key.replaceAll("_", "-")} must be an absolute path`);
  if (["plan", "install", "update"].includes(action)) { if (!o.bundle || !isAbsolute(o.bundle)) fail("INVALID_ARGUMENT", "--bundle must be an absolute path"); if (!/^[0-9a-f]{64}$/.test(o.manifest_sha256 ?? "")) fail("INVALID_ARGUMENT", "--manifest-sha256 must be the approved lowercase SHA-256 anchor"); }
  return o;
}
async function inventory(root, prefix = "") {
  const out = [];
  for (const name of (await readdir(root)).sort()) { const p = join(root, name); const rel = prefix ? `${prefix}/${name}` : name; const s = await lstat(p); if (s.isSymbolicLink()) fail("MODIFIED", `managed payload contains a link: ${rel}`); if (s.isDirectory()) out.push(...await inventory(p, rel)); else if (s.isFile()) out.push({ relativePath: rel, type: "file", mode: s.mode & 0o777, size: s.size, sha256: sha(await readFile(p)) }); else fail("MODIFIED", `unsupported managed payload: ${rel}`); }
  return out;
}
function treeDigest(files) { return sha(Buffer.from(files.map(x => `${x.relativePath}\0${x.type}\0${x.mode}\0${x.size}\0${x.sha256}\n`).join(""))); }
async function loadReceipt(root, binDir) {
  const p = join(root, RECEIPT); if (await kind(p) !== "file") fail("UNMANAGED", "private manager receipt is missing or not a regular file");
  const receiptStat = await lstat(p); if ((receiptStat.mode & 0o777) !== 0o600 || (typeof process.getuid === "function" && receiptStat.uid !== process.getuid())) fail("UNMANAGED", "private manager receipt permissions or owner are invalid");
  let r; try { r = JSON.parse(await readFile(p, "utf8")); } catch { fail("UNMANAGED", "private manager receipt is corrupt"); }
  if (r?.schemaVersion !== 2 || r.package !== PACKAGE || !/^\d+\.\d+\.\d+$/.test(r.activeVersion ?? "") || !r.versions || Array.isArray(r.versions) || !r.versions[r.activeVersion] || !r.launchers || Array.isArray(r.launchers) || r.runtime !== process.execPath || r.release?.repository !== REPOSITORY || r.release?.tag !== RELEASE_TAG || r.release?.manifestAsset !== MANIFEST_ASSET || !/^[0-9a-f]{64}$/.test(r.manifestSha256 ?? "") || !/^[0-9a-f]{64}$/.test(r.archiveSha256 ?? "")) fail("UNMANAGED", "private manager receipt is invalid");
  for (const [version, record] of Object.entries(r.versions)) if (!/^\d+\.\d+\.\d+$/.test(version) || record?.version !== version || record.root !== join(root, "versions", version) || !Array.isArray(record.files) || !/^[0-9a-f]{64}$/.test(record.treeSha256 ?? "")) fail("UNMANAGED", "receipt version ownership escapes the managed root");
  if (!Array.isArray(r.retainedVersions) || r.retainedVersions.some((version, i) => !r.versions[version] || version === r.activeVersion || r.retainedVersions.indexOf(version) !== i)) fail("UNMANAGED", "receipt retained versions are invalid");
  if (r.compatibility?.packageVersion !== r.activeVersion || r.compatibility?.skillRef !== RELEASE_TAG || r.compatibility?.catalogVersion !== CATALOG_VERSION || r.compatibility?.runtimeManifestSha256 !== r.manifestSha256) fail("UNMANAGED", "receipt compatibility identity is invalid");
  if (Object.keys(r.launchers).sort().join("\0") !== [...BINS].sort().join("\0")) fail("UNMANAGED", "receipt launcher set is invalid");
  for (const name of BINS) {
    const launcher = r.launchers[name];
    const expectedPath = binDir ? join(binDir, name) : launcher?.path;
    const cli = join(root, "versions", r.activeVersion, "lib", "node_modules", "@crissmoldovan", "workspace-governance", BIN_ENTRIES[name]);
    const expectedBytes = typeof expectedPath === "string" ? launcherText(r.runtime, cli, root, expectedPath) : null;
    if (!launcher || !isAbsolute(launcher.path ?? "") || launcher.path !== expectedPath || launcher.targetVersion !== r.activeVersion || typeof launcher.bytes !== "string" || launcher.bytes !== expectedBytes || !/^[0-9a-f]{64}$/.test(launcher.sha256 ?? "") || launcher.sha256 !== sha(expectedBytes)) fail("UNMANAGED", "receipt launcher ownership or digest is incoherent");
  }
  return r;
}
async function verifyVersion(root, record) { const vr = join(root, "versions", record.version); if (await kind(vr) !== "directory") fail("MODIFIED", `managed version ${record.version} is missing`); const got = await inventory(vr); if (treeDigest(got) !== record.treeSha256 || JSON.stringify(got) !== JSON.stringify(record.files)) fail("MODIFIED", `managed version ${record.version} was modified`); }
async function verifyLaunchers(receipt) { for (const name of BINS) { const r = receipt.launchers[name]; if (!r || await kind(r.path) !== "file" || sha(await readFile(r.path)) !== r.sha256) fail("CONFLICT", `owned launcher ${name} is missing, linked, or modified`); } }
function safeMember(name) { return name === "package" || (name.startsWith("package/") && !name.startsWith("/") && !name.split("/").includes("..") && !name.includes("\\")); }
async function validateBundle(o) {
  if (process.platform !== "linux" && process.platform !== "darwin") fail("UNSUPPORTED", `unsupported platform ${process.platform}; use manual installation guidance`);
  const manifestPath = join(o.bundle, MANIFEST_ASSET); if (await kind(manifestPath) !== "file") fail("INVALID_ARTIFACT", "release manifest is missing"); const mb = await readFile(manifestPath); if (sha(mb) !== o.manifest_sha256) fail("ANCHOR_MISMATCH", "release manifest does not match the carried approved anchor");
  let m; try { m = JSON.parse(mb); } catch { fail("INVALID_ARTIFACT", "release manifest is invalid JSON"); }
  if (m.schemaVersion !== 1 || m.artifactType !== "workspace-governance-offline-runtime" || m.package?.name !== PACKAGE || !/^\d+\.\d+\.\d+$/.test(m.package?.version ?? "") || m.package?.engines?.node !== ">=24.0.0" || (m.package?.lifecycleScripts ?? []).length !== 0) fail("INVALID_ARTIFACT", "release manifest package identity or lifecycle contract is invalid");
  const c = m.compatibility; if (c?.packageVersion !== m.package.version || c?.skillRef !== RELEASE_TAG || c?.catalogVersion !== CATALOG_VERSION) fail("INCOMPATIBLE", "package, skill, or catalog compatibility identity differs");
  if (m.release?.repository !== REPOSITORY || m.release?.tag !== RELEASE_TAG || m.release?.manifestAsset !== MANIFEST_ASSET) fail("INVALID_ARTIFACT", "release repository/tag/asset identity differs");
  const archive = join(o.bundle, m.archive?.file ?? ""); if (!inside(o.bundle, archive) || await kind(archive) !== "file") fail("INVALID_ARTIFACT", "archive path is invalid"); const ab = await readFile(archive); if (ab.length !== m.archive.size || sha(ab) !== m.archive.sha256) fail("INVALID_ARTIFACT", "archive digest or size differs");
  const npm = process.env.WORKSPACECTL_INSTALL_NPM || "npm"; const tar = process.env.WORKSPACECTL_INSTALL_TAR || "tar";
  const names = run(tar, ["-tzf", archive]).split("\n").filter(Boolean); const verbose = run(tar, ["-tvzf", archive]).split("\n").filter(Boolean); if (!names.length || names.length !== verbose.length) fail("INVALID_ARTIFACT", "archive inventory is invalid"); for (let i=0;i<names.length;i++) if (!safeMember(names[i]) || !["-", "d"].includes(verbose[i][0])) fail("INVALID_ARTIFACT", `archive contains an unsafe path or link: ${names[i]}`);
  const expected = new Set(m.content.map(x => x.path)); const regular = names.filter((_, i) => verbose[i][0] === "-"); if (regular.length !== expected.size || regular.some(x => !expected.has(x))) fail("INVALID_ARTIFACT", "archive regular-file inventory differs from manifest");
  return { manifest: m, archive, npm, tar };
}
function shQuote(value) { return `'${value.replaceAll("'", `'\\''`)}'`; }
function launcherText(node, cli, root, path) { return `#!/bin/sh\n# workspacectl-managed-launcher-v2\nset -eu\nexport WORKSPACECTL_INSTALL_PREFIX=${shQuote(root)}\nexport WORKSPACECTL_LAUNCHER=${shQuote(path)}\nexport WORKSPACECTL_RUNTIME_PATH=${shQuote(node)}\nexec ${shQuote(node)} ${shQuote(cli)} "$@"\n`; }
async function acquire(root) { await mkdir(root, { recursive: true, mode: 0o700 }); const lock = join(root, ".manager-lock"); try { await mkdir(lock, { mode: 0o700 }); } catch (e) { if (e?.code === "EEXIST") fail("BUSY", "another runtime lifecycle operation holds the manager lock"); throw e; } return async () => rm(lock, { recursive: true, force: true }); }
async function exclusiveFile(path, bytes, mode) { const dir = await mkdtemp(join(dirname(path), ".launcher-")); const candidate = join(dir, basename(path)); try { await writeFile(candidate, bytes, { mode }); await chmod(candidate, mode); await link(candidate, path); } catch (e) { if (e?.code === "EEXIST") fail("CONFLICT", `target became occupied: ${path}`); throw e; } finally { await rm(dir, { recursive: true, force: true }); } }
async function restoreMovedNoReplace(moved, path) { try { await link(moved, path); } catch (e) { if (e?.code === "EEXIST") fail("CONFLICT", `target became occupied while preserving a concurrent replacement: ${path}`); throw e; } await unlink(moved); }
async function quarantineOwned(path, digest) {
  if (await kind(path) !== "file") fail("CONFLICT", `owned target changed: ${path}`);
  const before = await stat(path); if (sha(await readFile(path)) !== digest) fail("CONFLICT", `owned target changed: ${path}`);
  const privateDir = await mkdtemp(join(dirname(path), ".workspacectl-private-")); await chmod(privateDir, 0o700); const moved = join(privateDir, "owned");
  try {
    if (process.env.WORKSPACECTL_TEST_REPLACE_BEFORE_UNLINK === path) { await rename(path, `${path}.displaced`); await writeFile(path, "concurrent replacement\n", { mode: 0o755 }); }
    await rename(path, moved);
  } catch (e) { await rm(privateDir, { recursive: true, force: true }); throw e; }
  const movedStat = await stat(moved); const movedDigest = sha(await readFile(moved));
  if (movedStat.dev !== before.dev || movedStat.ino !== before.ino || movedDigest !== digest) {
    try { await restoreMovedNoReplace(moved, path); await rm(privateDir, { recursive: true, force: true }); } catch (e) { if (e instanceof Refusal) throw e; throw e; }
    fail("CONFLICT", `owned target changed concurrently and replacement was preserved: ${path}`);
  }
  if (process.env.WORKSPACECTL_TEST_REPLACE_AFTER_UNLINK === path) await writeFile(path, "concurrent replacement\n", { mode: 0o755 });
  try { await link(moved, path); } catch (e) { if (e?.code === "EEXIST") fail("CONFLICT", `replacement appeared after owned target was quarantined: ${path}`); throw e; }
  const guard = await stat(path); if (guard.dev !== movedStat.dev || guard.ino !== movedStat.ino) fail("CONFLICT", `owned target guard changed concurrently: ${path}`);
  return { path, digest, privateDir, moved, movedStat, released: false };
}
async function releaseQuarantined(transaction) {
  const released = join(transaction.privateDir, "released"); await rename(transaction.path, released); const moved = await stat(released);
  if (moved.dev !== transaction.movedStat.dev || moved.ino !== transaction.movedStat.ino || sha(await readFile(released)) !== transaction.digest) {
    await restoreMovedNoReplace(released, transaction.path);
    fail("CONFLICT", `launcher changed during quarantine release and replacement was preserved: ${transaction.path}`);
  }
  transaction.released = true;
}
async function rollbackQuarantined(transaction) {
  if (transaction.released) {
    try { await link(transaction.moved, transaction.path); } catch (e) { if (e?.code === "EEXIST") return; throw e; }
  }
  try { const current = await stat(transaction.path); if (current.dev === transaction.movedStat.dev && current.ino === transaction.movedStat.ino) await rm(transaction.privateDir, { recursive: true, force: true }); } catch {}
}
async function replaceOwned(path, oldDigest, bytes) { const guard = `${path}.workspacectl-guard-${process.pid}`; if (await kind(path) !== "file" || sha(await readFile(path)) !== oldDigest) fail("CONFLICT", `owned launcher changed: ${path}`); await link(path, guard); try { const a = await stat(path), b = await stat(guard); if (a.dev !== b.dev || a.ino !== b.ino) fail("CONFLICT", `owned launcher changed concurrently: ${path}`); await unlink(path); if (process.env.WORKSPACECTL_TEST_REPLACE_AFTER_UNLINK === path) await writeFile(path, "concurrent replacement\n", { mode: 0o755 }); try { await exclusiveFile(path, bytes, 0o755); } catch (e) { if (await kind(path) === "absent") await link(guard, path); throw e; } } finally { await rm(guard, { force: true }); } }
async function stageVersion(o, validated, versionRoot) { const version = validated.manifest.package.version; const staging = await mkdtemp(join(o.root, `.staging-${version}-`)); try { const cache = join(staging, ".npm-cache"); const outcome = spawnSync(validated.npm, ["install", "--global", "--prefix", staging, "--offline", "--ignore-scripts", "--no-audit", "--no-fund", "--cache", cache, validated.archive], { encoding: "utf8", env: process.env, timeout: 120000 }); if (outcome.error || outcome.status !== 0) fail("INSTALL_FAILED", "offline scripts-disabled npm installation failed"); await rm(cache, { recursive: true, force: true }); const pkg = join(staging, "lib", "node_modules", "@crissmoldovan", "workspace-governance"); const meta = JSON.parse(await readFile(join(pkg, "package.json"), "utf8")); if (meta.name !== PACKAGE || meta.version !== version) fail("INVALID_ARTIFACT", "installed package identity differs"); for (const n of BINS) if (await kind(join(pkg, validated.manifest.package.bins[n])) !== "file") fail("INVALID_ARTIFACT", `installed package lacks ${n}`); await rm(join(staging, "bin"), { recursive: true, force: true }); await rm(join(pkg, "node_modules", ".bin"), { recursive: true, force: true }); await rename(staging, versionRoot); } catch (e) { await rm(staging, { recursive: true, force: true }); throw e; } const files = await inventory(versionRoot); return { version, root: versionRoot, files, treeSha256: treeDigest(files) }; }
async function install(o, validated) {
  let release = await acquire(o.root); try {
    if (await kind(join(o.root, RECEIPT)) === "file") { const current = await loadReceipt(o.root, o.bin_dir); for (const v of Object.values(current.versions)) await verifyVersion(o.root, v); await verifyLaunchers(current); if (current.activeVersion === validated.manifest.package.version && current.manifestSha256 === o.manifest_sha256) return { action: o.action, applied: false, noOp: true, activeVersion: current.activeVersion }; if (o.action !== "update") fail("CONFLICT", "a managed runtime already exists; use update with a different anchored version"); const version = validated.manifest.package.version, versionRoot = join(o.root, "versions", version); if (current.versions[version] || await kind(versionRoot) !== "absent") fail("CONFLICT", "update version root is already occupied"); const record = await stageVersion(o, validated, versionRoot); const next = {}; try { for (const name of BINS) { const p = current.launchers[name].path, cli = join(versionRoot, "lib", "node_modules", "@crissmoldovan", "workspace-governance", validated.manifest.package.bins[name]); const bytes = launcherText(process.execPath, cli, o.root, p); await replaceOwned(p, current.launchers[name].sha256, bytes); next[name] = { path: p, sha256: sha(bytes), targetVersion: version, bytes }; } } catch (e) { await rm(versionRoot, { recursive: true, force: true }); throw e; } current.retainedVersions = [...new Set([...(current.retainedVersions ?? []), current.activeVersion])]; current.versions[version] = record; current.activeVersion = version; current.launchers = next; current.manifestSha256 = o.manifest_sha256; current.archiveSha256 = validated.manifest.archive.sha256; current.compatibility = { ...validated.manifest.compatibility, runtimeManifestSha256: o.manifest_sha256 }; await writeFile(join(o.root, RECEIPT), jsonBytes(current), { mode: 0o600 }); return { action: "update", applied: true, activeVersion: version, retainedVersions: current.retainedVersions }; }
    const unknownRoot = (await readdir(o.root)).filter(name => name !== ".manager-lock"); if (unknownRoot.length) fail("CONFLICT", "managed root is occupied without a valid receipt");
    for (const name of BINS) if (await kind(join(o.bin_dir, name)) !== "absent") fail("CONFLICT", `launcher path is occupied: ${join(o.bin_dir, name)}`);
    const version = validated.manifest.package.version, versionRoot = join(o.root, "versions", version); if (await kind(versionRoot) !== "absent") fail("CONFLICT", "version root is occupied without a valid receipt"); await mkdir(join(o.root, "versions"), { recursive: true, mode: 0o700 }); await mkdir(o.bin_dir, { recursive: true, mode: 0o700 }); const staging = await mkdtemp(join(o.root, `.staging-${version}-`));
    await rm(staging, { recursive: true, force: true }); const record = await stageVersion(o, validated, versionRoot); const files = record.files; const launchers = {}; const created = []; try { for (const name of BINS) { const p = join(o.bin_dir, name), cli = join(versionRoot, "lib", "node_modules", "@crissmoldovan", "workspace-governance", validated.manifest.package.bins[name]); const bytes = launcherText(process.execPath, cli, o.root, p); await exclusiveFile(p, bytes, 0o755); created.push(p); launchers[name] = { path: p, sha256: sha(bytes), targetVersion: version, bytes }; } } catch (e) { for (const p of created) await rm(p, { force: true }); await rm(versionRoot, { recursive: true, force: true }); throw e; }
    const compatibility = { ...validated.manifest.compatibility, runtimeManifestSha256: o.manifest_sha256 }; const receipt = { schemaVersion: 2, package: PACKAGE, release: { repository: REPOSITORY, tag: RELEASE_TAG, manifestAsset: MANIFEST_ASSET }, manifestSha256: o.manifest_sha256, archiveSha256: validated.manifest.archive.sha256, activeVersion: version, runtime: process.execPath, compatibility, versions: { [version]: { version, root: versionRoot, files, treeSha256: treeDigest(files) } }, launchers, retainedVersions: [] }; await writeFile(join(o.root, RECEIPT), jsonBytes(receipt), { mode: 0o600 }); await chmod(join(o.root, RECEIPT), 0o600); return { action: o.action, applied: true, noOp: false, activeVersion: version, launchers: Object.fromEntries(BINS.map(n => [n, launchers[n].path])) };
  } finally { await release(); }
}
async function removeInstall(o) { const release = await acquire(o.root); try { const r = await loadReceipt(o.root, o.bin_dir); for (const v of Object.values(r.versions)) await verifyVersion(o.root, v); await verifyLaunchers(r); const known = new Set(Object.keys(r.versions)); const found = await readdir(join(o.root, "versions")); if (found.some(name => !known.has(name))) fail("CONFLICT", "versions container contains unknown content; nothing was removed"); if (o.preserve_version && !r.versions[o.preserve_version]) fail("INVALID_ARGUMENT", "--preserve-version must name an exactly owned version"); const quarantined = []; try { for (const n of BINS) quarantined.push(await quarantineOwned(r.launchers[n].path, r.launchers[n].sha256)); for (const transaction of quarantined) await releaseQuarantined(transaction); } catch (e) { for (const transaction of quarantined.reverse()) await rollbackQuarantined(transaction); throw e; } for (const transaction of quarantined) await rm(transaction.privateDir, { recursive: true, force: true }); const removedVersions = []; for (const [version, record] of Object.entries(r.versions)) if (version !== o.preserve_version) { await rm(record.root, { recursive: true }); removedVersions.push(version); } if (o.preserve_version) { const backup = { schemaVersion: 2, package: PACKAGE, release: r.release, manifestSha256: r.manifestSha256, archiveSha256: r.archiveSha256, preservedVersion: o.preserve_version, version: r.versions[o.preserve_version], compatibility: r.compatibility, runtime: r.runtime }; await writeFile(join(o.root, "backup-receipt.json"), jsonBytes(backup), { mode: 0o600 }); } else await rmdir(join(o.root, "versions")); await rm(join(o.root, RECEIPT)); return { action: "remove", applied: true, removedVersions, preservedVersion: o.preserve_version ?? null, preserved: ["config", "catalog", "state", "plans", "repositories", "skills"] }; } finally { await release(); try { if ((await readdir(o.root)).length === 0) await rm(o.root, { recursive: true }); } catch {} } }
async function rollbackInstall(o) { const release = await acquire(o.root); try { const r = await loadReceipt(o.root, o.bin_dir); for (const v of Object.values(r.versions)) await verifyVersion(o.root, v); await verifyLaunchers(r); const target = o.version ?? [...(r.retainedVersions ?? [])].reverse().find(v => v !== r.activeVersion); if (!target || !r.versions[target] || target === r.activeVersion) fail("INVALID_ARGUMENT", "rollback target must name a retained verified version"); const paths = { workspacectl: "dist/cli.js", "workspacectl-mcp": "dist/mcp-cli.js" }; const next = {}; for (const name of BINS) { const old = r.launchers[name], cli = join(r.versions[target].root, "lib", "node_modules", "@crissmoldovan", "workspace-governance", paths[name]); if (await kind(cli) !== "file") fail("MODIFIED", `rollback target lacks ${name}`); const bytes = launcherText(r.runtime, cli, o.root, old.path); await replaceOwned(old.path, old.sha256, bytes); next[name] = { path: old.path, sha256: sha(bytes), targetVersion: target, bytes }; } const previous = r.activeVersion; r.activeVersion = target; r.launchers = next; r.retainedVersions = [...new Set([...(r.retainedVersions ?? []).filter(v => v !== target), previous])]; await writeFile(join(o.root, RECEIPT), jsonBytes(r), { mode: 0o600 }); return { action: "rollback", applied: true, activeVersion: target, retainedVersions: r.retainedVersions }; } finally { await release(); } }
async function main() { const o = parse(process.argv.slice(2)); await refuseSymlinkAncestors(o.root); await refuseSymlinkAncestors(o.bin_dir); let result;
  if (["status", "remove", "rollback"].includes(o.action)) { if (o.action === "status") { try { const r = await loadReceipt(o.root, o.bin_dir); await verifyVersion(o.root, r.versions[r.activeVersion]); await verifyLaunchers(r); result = { action: "status", managed: true, activeVersion: r.activeVersion, compatibility: r.compatibility }; } catch (e) { if (e instanceof Refusal && e.code === "UNMANAGED") result = { action: "status", managed: false }; else throw e; } } else if (o.action === "rollback") { const r = await loadReceipt(o.root, o.bin_dir); const target = o.version ?? [...(r.retainedVersions ?? [])].reverse().find(v => v !== r.activeVersion); if (!o.yes) result = { action: "rollback", applied: false, requiresYes: true, activeVersion: r.activeVersion, targetVersion: target ?? null }; else result = await rollbackInstall(o); } else if (!o.yes) { const r = await loadReceipt(o.root, o.bin_dir); if (o.preserve_version && !r.versions[o.preserve_version]) fail("INVALID_ARGUMENT", "--preserve-version must name an exactly owned version"); result = { action: "remove", applied: false, requiresYes: true, activeVersion: r.activeVersion, launchers: BINS.map(n => r.launchers[n].path), versionRoots: Object.values(r.versions).map(v => v.root), preserveVersion: o.preserve_version ?? null }; } else result = await removeInstall(o);
  } else { const v = await validateBundle(o); if (!o.yes) result = { action: o.action === "plan" ? "install" : o.action, applied: false, requiresYes: true, package: v.manifest.package, compatibility: v.manifest.compatibility, destination: { root: o.root, binDir: o.bin_dir } }; else result = await install(o, v); }
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}
main().catch(e => { const code = e instanceof Refusal ? e.code : "INTERNAL"; process.stderr.write(`${JSON.stringify({ error: { code, message: e instanceof Error ? e.message : String(e) } })}\n`); process.exitCode = code === "CONSENT_REQUIRED" ? 4 : code === "CONFLICT" || code === "BUSY" || code === "MODIFIED" || code === "UNMANAGED" ? 5 : 2; });
